hexrd/cli/find_orientations.py, hexrd/findorientations.py
Hi @joelvbernier. I started taking a look at the find_orientations() code, 
and I was able to run a test on it successfully (for the 8 detector example).
However, I noticed that the `find_orientations()` function writes out
the results rather than returning them. I thought that it might make
it easier for us to write tests, and plot things in the GUI, if the
`find_orientations()` returned the data. So in this PR, it does that,
and also, the writing out of data is now in the CLI code instead of in the 
`find_orientations()` function.
Let me know what you think of the changes.
=> Return results from find_orientations()

hexrd/findorientations.py
We will probably not be saving the eta omega maps generated
by the GUI here.
=> Make saving optional in generate_eta_ome_maps

hexrd/instrument.py
This PR parallelizes `extract_polar_maps`. @joelvbernier I used the finer grain parallize you suggest. One my 4 core laptop I see the time go from 157 sec to 50 sec, more cores will show even better improvement. I am also only calculating `eta_edges` once for the first detector and reusing it.
=> Extract polar maps parallel

hexrd/findorientations.py
This moves the majority of the code used to create the min samples
and the mean reflections per grain, for the clustering, into
a separate function. This is done so that we can call this function
from the GUI.
I did a CLI `hexrd find-orientations ...` before and after test,
to make sure the output didn't change, and a diff shows that the
output appears to be the same.
=> Move code to create clustering params into method

hexrd/WPPF.py, hexrd/material.py, hexrd/symmetry.py
merging changes to WPPF module.
=> New material

hexrd/cli/fit_grains.py
Fixes CLI exception when fit_grains runs find_orientations.
=> Fix name of find_orientations module

hexrd/imageutil.py, hexrd/instrument.py
fixed the buffer key in the write to YAML, and added some new snip background estimation algorithms.
=> add fast and 2-d snip; fix kw

hexrd/cli/fit_grains.py, hexrd/fitgrains.py, hexrd/instrument.py
Reorganizes/augments fit-grains logic to handle file I/O separately from the calculations.
* All changes apply to hexrdgui
* Does not change hexrd CLI
* Updates GrainsDataWriter to write to either filename or numpy array
* Updates instrument to make writing spots files optional
=> Fit grains return results

hexrd/config/dumper.py, hexrd/config/instrument.py, hexrd/config/loader.py, hexrd/instrument.py
This is to support numpy array's in the instrument panel buffer.
Fixes #28
=> Add PyYAML Loader and Dumper to handle numpy.ndarray

hexrd/constants.py, hexrd/instrument.py
Lots of work to be done, but this simulator works for now.
=> added simple simulator

hexrd/cli/fit_grains.py
Some weirdness in how the different args were handled.  Also removed a hanging assignment to `cfg.fit_grains.qbar`, which is unnecessary.  Now behaves as intended.
=> fix arg logic in fit-grains CLI

hexrd/distortion/__init__.py, hexrd/distortion/distortionabc.py, hexrd/distortion/ge_41rt.py, hexrd/distortion/identity.py, hexrd/distortion/nyi.py, hexrd/distortion/registry.py, hexrd/distortion/utils.py, hexrd/fitting/grains.py, hexrd/instrument.py, hexrd/transforms/xf.py, hexrd/transforms/xfcapi.py, hexrd/xrdutil.py
This PR has the new distortion package implemented.  Tested instrument initialization, and applicaiton via the hexrdgui in polarview.
=> New distortion

.github/workflows/test.yml
See: https://github.com/numpy/numpy/issues/17216
=> Work around issue with setuptools and numpy

hexrd/material.py, hexrd/unitcell.py
When a material's `sgnum` gets set, also set the unitcell's `sgnum` if it has been created.
When the unitcell's `sgnum` is set, update the point group and Laue group.
=> Add a few more updates for setters

hexrd/WPPF.py, hexrd/crystallography.py, hexrd/material.py
`WPPF.Material_LeBail` can now be initialized by passing a list or an instance of `material.Material` class. This should resolve #101.
Additionally, the `bkgmethod` argument to the `LeBail` class is now a dictionary. If `spline` is chosen, the value is `None`, if `chebyshev` is chosen, then the value is the polynomial degree. This degree needs to be an integer.
=> WPPF feature

hexrd/crystallography.py, hexrd/matrixutil.py
Fixes #91 -- at least the contribution from matrixutil, which was a very old module.
=> fixed matrixutil deprecations

hexrd/material.py
As mentioned in issue #124, the material lattice parameter set logic now depends on the length of the input.
=> Material lattice prameter setter

hexrd/unitcell.py
Fix density computation and make it a property such that it is recalculated when space group or lattice parameters are changed.
=> Density computation

.github/workflows/package.yml
CentOS 6 has reached the end of its life!
=> Move package container to CentOS 7

hexrd/material.py
make sure the kev is checked to be a valWUnit type. If not, then change it to such and set Material.beamEnergy using the valWUnit type.
=> Fix to material editor in hexrdgui

hexrd/material.py
=> Update scattering factors in planedata once energy is updated

.github/workflows/container_build.sh, .github/workflows/package.yml
So move back to latest. See https://github.com/conda/conda-build/issues/4182 for more details.
=> Looks like the conda-build issue is resolve in 3.21.4

hexrd/WPPF.py
write out all the info to hdf5 file. The groups created are `Parameters`, `Phases` and `Spectrum`. This just adds the write capabilities. The initialization of the `LeBail` class from this hdf5 will be part of a later commit.
=> Wppf h5 dump

hexrd/distortion/__init__.py, hexrd/distortion/dexela_2923.py, hexrd/distortion/ge_41rt.py
Simple in-plane distortion function for the dexela detectors.  Includes a simple unit test, but will need to integrate it in CI later.
=> add distortion function for dexela 2923

hexrd/instrument.py
simple utility function for computing the angular resolution of an instrument.
=> add function to compute angular res of instrument

hexrd/instrument.py
some additional cleanup.  Tested and looks ok.
=> Resolution function

hexrd/WPPF.py, hexrd/utils/multiprocess_generic.py
Run LeBail fits for each row of intensity for different azimuths using multiprocessing. Tested with 80.725 keV Ceria dataset from. One thing to improve is to put in the right workflow for automated refinement so that convergence is always good. Right now everything is refined by default. Results below. This dataset is the best case scenario.
=> Intensity extraction

hexrd/findorientations.py
Extract the code to label spots so that we can also use it in
hexrdgui.
=> Extract label_spots function in findorientations

hexrd/material.py, hexrd/mksupport.py
@joelvbernier This should fix #172. The mechanism is exactly the same as you commented. The initialization reads the hkl list from HDF5 file and sets exclusions based on which reflections are present there.
=> set exclusion from hkl list in material HDF5 file.

hexrd/imageutil.py
necessary for properly working with the GUI's version of PolarView that includes NaN padding around the detectors.
=> nan handling in astropy convolve

conda.recipe/meta.yaml, setup.py
=> remove redundant package reqs and alphabetize

hexrd/material.py
=> adding default stifness. All zeros.

hexrd/config/findorientations.py, hexrd/findorientations.py, hexrd/transforms/xfcapi.py, hexrd/xrdutil.py
Added map filtering to address artifacts I was seeing in recent data (details to follow).
=> added eta_ome filtering

hexrd/WPPF.py, hexrd/instrument.py, hexrd/utils/multiprocess_generic.py
Removed the dependence of mixing factor on a polynomial in theta. Instead this is replaced by the mixing factor, η, given in P. Thompson, D.E. Cox & J.B. Hastings, J. Appl. Cryst.,20,79-83, 1987. This also changes the convention a little bit where  η=1 is pure Lorentzian and  η=0 is pure Gaussian. Leads a way. more stable optimization behavior.
=> WPPF update

hexrd/findorientations.py
I'm mostly just doing this so we can call the function in hexrdgui...
=> Move code to filter maps if requested to function

hexrd/findorientations.py
This is so that in the GUI, we can clean the maps without labeling
the spots.
=> Move map cleaning into a function

hexrd/unitcell.py
fixed typo in `unitcell.CalcStar` which was breaking the hkl generation.
=> URGENT -- MASTER BROKEN w/o THIS FIX

hexrd/instrument.py
=> include multiplicity in intensity calculation.

hexrd/material.py
Default name was not getting set.
=> set name of default material

hexrd/instrument.py
This makes the output better suited for a discrete model using these as evaluation points.
=> change to bool from index

hexrd/fitting/fitpeak.py, hexrd/fitting/peakfunctions.py, hexrd/xrdutil.py
Tested these changes with new (uncommitted) powder calibration routines.
=> fixes in anticipation of new calibration classes

hexrd/material.py, hexrd/unitcell.py
fixing the update of lattice parameter to correspond to update of space group number. 
Fix for issue #205
=> Update lattice parameter when space group is updated.

hexrd/instrument.py
Looks like this was missing...
=> Set panel buffer for np.ndarray

hexrd/WPPF.py
This is to help out with issue https://github.com/HEXRD/hexrdgui/issues/782 in the GUI
=> adding background method dict structure.

hexrd/instrument.py
Added module-level utility function, and a `pixel_spherical_angles` property on the `PlanarDetector` class.  Works, but could use optimization.
=> added calc of pixel spherical angles

hexrd/material.py
Initialize new planedata and unitcell class when lattice parameters are changed. Issue #217
=> Material fix

hexrd/instrument.py, hexrd/xrdutil.py
utility method for pixel resolution stats.
=> added module method

hexrd/imageseries/process.py
Before, it was just iterating over the un-processed images
underneath. We need it to perform the processing, though.
Fix the iterator to perform the processing.
=> Fix ProcessedImageSeries __iter__

hexrd/material.py, hexrd/unitcell.py
Improvement for the `U.setter` function in `unitcell` class.
Added `U.setter` to material class. RIght now everything is passed as 1-D or 2-D arrays depending on the isotropic and anisotropic cases resp.
=> Unitcell U setter

hexrd/material.py
=> Material dmin fix

hexrd/resources/pxrdip_reference_config.yml
Using values from various calibrations, updated the default instrument to be closer to what is typically observed.
=> updated reference pxrdip

hexrd/constants.py, hexrd/findorientations.py, hexrd/imageutil.py
a little reorganization -- the util routine for peak finding was hidden inside `hexrd.findorientations`
=> moved 2d peak detection to imageutil

hexrd/material.py
Make sure numbers are updated before updating everything.
=> Structure setters

hexrd/instrument.py
This generates ring parameters one time in its own loop, and then
swaps the previous ordering of the loops so that looping over the
images is on the outside and looping over the rings is on the inside.
This results in each image only being loaded once, rather
than once for each ring, as it was before. Since loading the images is
time consuming, this results in a nice speedup.
For the GE example in the examples repository, my performance improved
from 17 seconds to 5 seconds, and the same result was obtained.
=> Improve performance of eta omega map generation

hexrd/instrument.py
Since this is an expensive computation, memoizing can help a lot.
=> Memoize pixel_solid_angle results

hexrd/imageseries/load/imagefiles.py
This opens the fabio files by using `fabio.open()` as a context manager
similar to the regular python `open()` function ([see the fabio documentation](http://www.silx.org/doc/fabio/0.11.0/api/modules.html#fabio.open)).
This causes the fabio files to be closed when the context is exited, and
it fixes an issue where an `OSError: [Errno 24] Too many open files` would
be raised if there were too many image files being loaded (over 1024 for
several operating systems).
This also eliminates saving `fabioimage` in the `FileInfo` class to allow
the fabio image to be closed.
I did a tiny bit of benchmarking using 10000 images files, and I didn't see
much of a performance difference caused by the changes in this commit.
Fixes: #261
=> Close fabio files after reading them

hexrd/fitting/fitpeak.py
Small simple fix to peak fitting. Also remembering how to submit fixes before attempting larger update to peak fitting module.
=> Fixing long standing bug in multipeak fitting non-linear backgrounds.

hexrd/material.py, hexrd/unitcell.py
initialize om in unitcell and make sure charge is initialized to 0 in `Materials._readCIF`. This fixes issue #274
=> Bug in initialization of unitcell.

hexrd/wppf/WPPF.py
make sure number of points in fitting is not less than degree of polynomial.
=> chebyshev polynomial background edge case

hexrd/grainmap/__init__.py, hexrd/grainmap/nfutil.py, hexrd/grainmap/tomoutil.py, hexrd/grainmap/vtkutil.py, scripts/preprocess_tomo_mask.py, scripts/process_nf.py
Adding nf utilities (contained in a new grainmap module), processing script (process_nf.py),and tomography preprocessing for masking (preprocess_tomo_.py). Scripts are located in the scripts folder.
Update also consolidates image preprocessing and masking features spread across different versions.  Lastly, new beam stop image masking options are available.
This nf processing does not contain binary image bit-packing which could provide performance increases.
=> NF Processing and Scripting

hexrd/utils/decorators.py, tests/test_memoize.py
If the maxsize of the cache is about to be exceeded, the least
recently used item in the cache will be removed.
The maxsize defaults to 5. We can change it if needed.
This also adds a `cache_info()` function similar to `functool.lru_cache()`'s
`cache_info()` function, which returns hits, misses, current size and max size
of the memoized function.
Tests were also added that seem to confirm that the decorator works properly.
=> Add a maxsize argument to memoize with LRU removal

hexrd/cli/find_orientations.py
This is so we can call this function in the GUI...
=> Separate out write_scored_orientations() function

hexrd/instrument.py
Added the ability to specify (rather than autogenerate) eta bin centers in `HEDMInstrument.extract_line_positions`.  The involved a pass-thru for a similar arg in `PlanarDetector.make_powder_rings`.  There are likely more changes to this function coming, as we should use it for interpolating Laue spots (for Laue cal among other things).
=> added eta patch specification option

hexrd/indexer.py, hexrd/instrument.py
Now `collapse_eta` returns properly summed intensities.
Fixes: #288
=> adjust output of line position extraction

hexrd/cli/main.py, setup.py
=> Add --version option to cli

hexrd/instrument.py
Finally added the option to apply distortion (or inverse) in the transformation methods taking (2θ, η) → (x, y) and (x, y) → (2θ, η); namely the `PlanarDetector.angles_to_cart()` and `PlanarDetector.cart_to_angles()` methods.  The previous behavior was to assume that (x, y) were always in the "ideal" (read: undistorted) frame.  This is preserved in the default value of the new kwarg: `apply_distortion=False`.  Of course if `self.distortion is not None` is `False`, then `apply_distortion=True` has no effect.
Documentation for the affected methods has been updated as well.
=> added kwarg for distortion application in cart<->ang transforms

hexrd/wppf/parameters.py
Fixed this based on @psavery's comments.
=> check if vary is either bool ornumpy bool type

hexrd/instrument.py
modify the form of lp correction based on the form in "Two dimensional x-ray diffraaction" by Bob He. Also introduces the ability to pass unpolarized as an argument. This modifies the computation of the polarization factor.
=> modify expression for Lorentz factor

hexrd/material.py
=> replace "_" with "" in the HM symbol.

.github/workflows/package.yml
Looks like the issue we were running into have now been fixed upstream.
=> Revert fixed conda version

hexrd/fitting/calibration.py
This is a cleaned-up version of the previously munged PR #368 
What this entails is the first step in incorporating the auto powder calibrator classes that are working in `hexrdgui` here with the idea that they should eventually be imported _from_ here into the GUI.
=> added auto powder cal classes

hexrd/constants.py, hexrd/rotations.py
Added utility function `expMapOfQuat` as well as some enhanced docstrings.
=> Rotations features

hexrd/wppf/WPPF.py
The issue was due to a wrong range of two theta over which the background was estimated. This PR fixes the related issue #382
=> fixing issues with spline background estimation

hexrd/fitting/calibration.py
So that we can call this function in hexrdgui as well
=> Move generating parameter names into a function

hexrd/fitting/calibration.py
Fix parameter name expmap_c indices and replace parameter name expmap_c with xi
=> Fix parameter names

hexrd/rotations.py, hexrd/xrdutil/utils.py
Minor update to the code for doing planar projections of unit 3-vectors on the sphere.
=> fixes to projection code

hexrd/material.py, hexrd/mksupport.py
read it if available in the file. if not, default values are used. Note: evrything saved in degrees, but internally handled correctly. Fixes issue #327
=> save two theta width in h5 file. 

hexrd/rotations.py
1. Added units specification kwarg to `RotMatEuler` class to handle degrees
2. Added `exponential_map` property with setter to get/set the rotation encoded by a `RotMatEuler` instance.
passed the following:
```
import numpy as np
from hexrd import constants as cnst
from hexrd.rotations import RotMatEuler, rotMatOfExpMap
rme = RotMatEuler(angles=cnst.zeros_3, axes_order='xyz', extrinsic=True, units='degrees')
new_angles = np.r_[0., -30., 0.]
rme.angles = new_angles
rmat_from_angles = rme.rmat
new_rmat = rotMatOfExpMap(np.radians(30.)*np.c_[1., 0., 0.].T)
rme.rmat = new_rmat
angles_from_rmat = rme.angles
rme.units = 'radians'
print(np.max(rme.angles - np.radians(np.r_[30., 0., 0])))
rme.rmat = rmat_from_angles
print(np.max(rme.angles - np.radians(new_angles)))
```
=> Rotations update

hexrd/mksupport.py
only write hkl if shape is not (0,). 
Fixes: hexrd/hexrdgui#1154
=> Check shape of hkl array before write

hexrd/fitting/calibration.py
This fixes one of the checkboxes in hexrd/hexrdgui#1160
=> Use logger for InstrumentCalibrator

hexrd/calibration/plot_calibration.py, hexrd/instrument.py
Several updates were needed to `PlanarDetector.make_powder_rings` to fix the behavior of `HEDMInstrument.extract_line_positions`
=> Powder line extraction

hexrd/imageseries/load/hdf5.py
This adds the `__getstate__()` and `__setstate__()` functions to the
HDF5 imageseries adapter so that it can be pickled.
This is needed, for instance, when running fit-grains with more than
one grain on a system using "spawn" multiprocessing (such as Windows).
Otherwise, an error will occur.
The logic here mostly follows [the official python example](https://docs.python.org/3/library/pickle.html#handling-stateful-objects).
=> Make HDF5 imageseries pickleable

hexrd/matrixutil.py
Need this utility for several higher-level functions.
=> added Wahba solver

hexrd/constants.py, hexrd/fitting/calibration.py, hexrd/fitting/spectrum.py, hexrd/fitting/utils.py, hexrd/instrument.py, hexrd/rotations.py
This is another step in trying to finalize the design for the calibrator classes.  Added attributes to act as a container for calibration points, so you can set them.  Lots of tasks:
=> attribute for picks and logging

hexrd/crystallography.py
The `PlaneData` class is in need of some cleanup.  A few important features include 
There may be more...  @saransh13?
=> Plane data updates

hexrd/fitting/calibration.py, hexrd/instrument.py
- logging output in sx calibration
- auto period specification in `pull_spots` (*preferred*)
=> some tweaks to the HEDM calibration

hexrd/fitting/spectrum.py, hexrd/fitting/utils.py
This is to address some issues with the DCS profile function fitting.
@saransh13 -- please test this branch against the problematic data you have.
=> Spectrum fitting fixes

hexrd/xrdutil/phutil.py
This module will house the utilities needed for applying pinhole camera corrections to apparent Bragg angle.
=> add pinhole util module

hexrd/material.py
sync `Material.atominfo`, `Material.atomtype` and `Material.charge` to the updated values after `Material.remove_duplicate_atoms` is called.
=> Remove duplicate atom sync

hexrd/fitting/calibration.py, hexrd/instrument.py, hexrd/xrdutil/phutil.py
This branch adds the necessary utilities to apply the 2θ distortion associated with pinhole camera instruments (_e.g._, PXRDIP, TARDIS).
closes #463 
closes #464
=> Pinhole distortion

hexrd/instrument.py
Was `None`, which would be problematic for serialization to HDF5.
=> change default source_distance to inf

hexrd/fitting/calibration.py, hexrd/fitting/grains.py, hexrd/instrument.py, hexrd/xrdutil/phutil.py
Additional commits required to make the calibartion work.
=> Additional modifications to make tth_distortion for pinhole camera instruments functional

scripts/pinhole_2theta.py
A stand-alone script which calculates the Bragg angle correction for the pinhole substrate for PXRDIP and TARDIS, as described in Ref. [1], section III.C.
[1] Rygg et al, Rev. Sci Instrum. (2020). DOI = 10.1063/1.5129698
=> script to calculate pinhole 2theta

hexrd/imageseries/load/hdf5.py
Previous merge included some dubious logic casting entire datasets as arrays (_bad_ for big imageseries).  I think this is the better way to do it.  Big thanks to @psavery for pointing the unintended consequences of my previous implementation in PR #477.
=> fixed the bad choice of always casting as array

hexrd/material.py
As title says. Fixes issue #435
=> change default value of U for material to 6.33E-3 from 4E-7

hexrd/wppf/WPPF.py
Only the first phase fraction was updated. When trying to set the value, an error was raised. This PR fixes issue #488
=> fixing weird error with multi-phase Rietveld. 

hexrd/wppf/WPPF.py
catching cases when no parameters are refined. Instead of throwing error the "observed" intensities are updated.
=> wppf exception catching

hexrd/unitcell.py
=> add incoherent and coherent scattering to the absorption cross-section.

pyproject.toml, setup.py
The latest version of numba supports this.
=> Bump pip numpy version to 1.23

hexrd/instrument.py
Fixes issue [#1392](https://github.com/HEXRD/hexrdgui/issues/1392) in hexrdgui
=> Do not normalize solid angles. Will be done in the GUI.

hexrd/fitting/calibration.py, hexrd/instrument/cylindrical_detector.py, hexrd/instrument/hedm_instrument.py, hexrd/resources/tardis_reference_config.yml, hexrd/xrdutil/phutil.py, hexrd/xrdutil/utils.py
New class to perform structureless calibration when the line positions are not known. This branch is required for PR https://github.com/HEXRD/hexrdgui/pull/1484
Fixes: hexrd/hexrdgui#1447
=> Structureless calibration

hexrd/wppf/xtal.py
Instead use just builtin `complex`.
=> remove reference to np.complex

README.md
=> Add instructions for citation

hexrd/instrument/cylindrical_detector.py
All normalization is done in the GUI.
=> remove normalization in the _pixel_solid_angle function. 

hexrd/fitgrains.py
This adds an optional argument to `fit_grains()` named `check_if_canceled_func`. It should be a nullary function that returns a boolean.
If provided, it will be checked every 0.25 seconds while fit-grains is running to see if the operation should cancel.
If it returns `True`, the multiprocessing pool is terminated and `None` is returned.
Because we rely on the multiprocessing pool to cancel, if the cancel function is provided, we use the multiprocessing pool, even if there is only one process to run.
=> Add ability to cancel fit-grains programmatically

hexrd/wppf/WPPF.py, hexrd/wppf/wppfsupport.py
Ability to refine chebyshev background with other parameters after initial values are determined.
Needs additional changes in hexrdgui otherwise wppf package will be broken.
=> Backround refine

.github/workflows/package.yml
The [issue with anaconda-client](https://github.com/Anaconda-Platform/anaconda-client/issues/654) was resolved.
=> Remove urllib3 version pinning

hexrd/resources/instrument_templates/dual_dexelas.yml
This adds the "Dual Dexelas" instrument configuration
@psavery Any additional instruments we should include right now?
=> Add initial pre-configured instrument

scripts/pinhole_2theta.py
These fixes are required to run it.
=> Update numpy and qt in Ryan's pinhole script

hexrd/xrdutil/phutil.py
xy points on the detector past the critical beta have very high values and start appearing unrealistic. Just set any values to nan that are past the critical beta.
Note that we are not invalidating map values past the critical beta for now, because they actually appear okay when warping the polar view. This is because they move too far and disappear (which is actually what we want when warping to the polar view).
=> Invalidate sample layer past critical beta

hexrd/wppf/peakfunctions.py
=> redefining goodness of fit for wppf module

.github/workflows/package.yml, conda.recipe/conda_build_config.yaml
This build needs to be fixed
Fixes: #640
=> Add back osx-arm64 build

hexrd/constants.py, hexrd/distortion/dexela_2923.py, hexrd/findorientations.py, hexrd/fitting/peakfunctions.py, hexrd/fitting/utils.py, hexrd/gridutil.py, hexrd/indexer.py, hexrd/instrument/detector.py, hexrd/material/symmetry.py, hexrd/material/unitcell.py, hexrd/matrixutil.py, hexrd/rotations.py, hexrd/sampleOrientations/conversions.py, hexrd/sampleOrientations/rfz.py, hexrd/sampleOrientations/sampleRFZ.py, hexrd/transforms/xf.py, hexrd/utils/decorators.py, hexrd/wppf/derivatives.py, hexrd/wppf/peakfunctions.py, hexrd/wppf/xtal.py, hexrd/xrdutil/phutil.py, hexrd/xrdutil/utils.py
[Solving this issue](https://github.com/HEXRD/hexrd/issues/548)
Check the comment in that issue about the FIXME comment before merging.  Those functions are not currently covered by any tests, though most likely, only the USE_NUMBA branch has been being used by anyone recently,
=> Remove numba checks

hexrd/transforms/cpp_sublibrary/src/inverse_distortion.cpp, setup.py
Much faster, agrees with python version up to around 1e-12.
=> Use Zack's Eigen implementation of inverse distortion

hexrd/material/unitcell.py, tests/unitcell/test_vec_math.py
Added testcases for some of unitcell.py, though I don't know enough about the rest to write testcases for it.  Also bugfix on TransSpace from @saransh13, and some minor reformatting.
=> Unitcell testcases

hexrd/instrument/cylindrical_detector.py, hexrd/instrument/detector.py, hexrd/instrument/hedm_instrument.py, hexrd/instrument/planar_detector.py
- The calc_transmission function should not require a physics package
=> Do not require physics package

hexrd/distortion/__init__.py, hexrd/distortion/dexela_2923.py, hexrd/distortion/dexela_2923_quad.py, tests/test_distortion.py
Also enable both dexela distortions tests.
=> Integrate quad dexela distortion

docs/source/users/index.rst, hexrd/cli/fit_grains.py, tests/test_graindata.py
This adds some new features to the GrainData class, including saving/reading grains.out files, quaternions attribute, strain attribute and a select method. This also adds user documentation in the docs section.
=> Grain data update

docs/source/users/GrainData.rst
Added doc file I missed in last pull request.
=> added GrainData.rst file

tests/test_wppf.py
This just verifies that the goodness of the fit improves over time, and that the current debye waller factors for Rietveld and the lattice constant for LeBail arrive at their expected values.
=> Add a simple regression test for WPPF

setup.py
Here is the issue: https://github.com/jamesrhester/pycifrw/issues/14
=> Pin pycifrw until macos issue is fixed

hexrd/fitting/fitpeak.py
This function was renamed as of scipy 1.6.0.
=> Update `simps` from `scipy.integrate` to `simpson`

hexrd/xrdutil/phutil.py
These are necessary for correct pinhole corrections for FIDDLE.
=> Add required x-axis and eta shifts for Fiddle instrument

hexrd/material/material.py, hexrd/material/unitcell.py
As the title says, get chemical formula of the unit cell, correctly weighted by number of atoms in unit cell and occupancy.
=> compute chemical formula for material unitcell.

hexrd/wppf/WPPF.py
As mentioned above, the shift should use tan(theta). Instead the code was using tan(2theta). Fixing that.
=> missing factor of 0.5 in calculating the stacking fault shift.

hexrd/wppf/WPPF.py, hexrd/wppf/xtal.py
1. Use `np.empty()` for minor speedup
2. Ensure structure factor and two theta updates only occur when they are needed (for performance)
3. Update stacking fault and twin beta for Rietveld
=> A few more WPPF improvements
