HEXRD/hexrd

hexrd/instrument.py

Most of the time, when a user would call `make_powder_rings()`,
they probably passed a PlaneData object. However, the function is
also designed to accept a list of two theta values. It appears,
though, that if you pass it a list of two theta values, it misses
the creation of del_eta that is normally done if a PlaneData object
is passed in.
This adds in the missing variable. The function seems to work properly
if this variable is included.

Add missing del_eta to make_powder_rings

---

hexrd/imageseries/save.py

Currently, the npz reader expects the dtype to be in bytes ([here](https://github.com/joelvbernier/hexrd3/blob/2f841ffb7780a74af4f798c08aadd4a9160e5cbd/hexrd/imageseries/load/framecache.py#L68)).
The npz writer was not writing in bytes, which resulted in an
incompatibility between the two.
This commit modifies the writer to write out the npz dtype
in bytes so that the reader is able to read it correctly. It
fixes the incompatibility between the two.

Save the npz dtype as bytes

---

hexrd/imageseries/load/framecache.py

Files written with Python 2.7 will be numpy.bytes_, Python 3 will be numpy.str_. Decode according to this type.

Add check to type using to encode dtype

---

conda.recipe/meta.yaml

This is needed so conda uses that same version of python for build
and test. Plus anytime we have numpy as a dep we are tied to a
particular python version.

Specify Python version

---

hexrd/imageseries/load/array.py
hexrd/imageseries/stats.py
hexrd/imageseries/tests/test_stats.py

This updates the imageseries.stats.median() function to use chunks and return an intermediate image at each point, allowing the calling function to update a progress bar. I will follow up with another request applying these changes to other functions such average, max or percentile. Here is an example of the usage:
```python
import numpy as np
from hexrd import imageseries
stats = imageseries.stats
a = np.ones((50, 10, 6))
for i in range(a.shape[1]): # set values by row
a[:,i,:] = i
ims = imageseries.open(None, 'array', data=a)
def run_chunk(ims, nchunk):
img = np.zeros(ims.shape)
for i in range(nchunk):
img = stats.median(ims, chunk=(i, nchunk, img))
print("%d/%d\n" % (i, nchunk), img)
return img
```

Chunk stats

---

conda.recipe/meta.yaml

This cause issues when build the conda package on Windows.

Remove asterisk from python version

---

conda.recipe/meta.yaml

We are no longer prefixing our versions with 'v', so don't try to
remove it!

Don't remove 'v'

---

.github/workflows/main.yml

Only upload to main channel when we push a tag. Otherwise, push to
a prerelease channel.

Separate pushing tag and merge to master

---

hexrd/config/instrument.py
hexrd/config/material.py
hexrd/config/root.py

When config data is loaded from a file for the first time, store
the data on a member variable so that if the data is requested a
second time, it doesn't need to be read from the file again.
This also allows applications, such as hexrdgui, to set the config
data if the data has already been loaded into the application,
so that the data doesn't need to be loaded from the files again.

Cache config data from files. Allow setting the data.

---

hexrd/imageseries/process.py

This is required in order to run find_orientations with a
ProcessedImageSeries object.
If frames were specified, then a generator is returned which
yields the frames one at a time as they are iterated through.
Otherwise, the underlying image series' iterator is used.

Add __iter__ method to ProcessedImageSeries

---

hexrd/instrument.py
hexrd/xrdutil.py

This adds a static save method on `hexrd.xrdutil.EtaOmeMaps` (copied
directory from `hexrd.instrument.GenerateEtaOmeMaps.save()`), that
is used both by `EtaOmeMaps` and `GenerateEtaOmeMaps` to save their
data.
This is mostly done so that `EtaOmeMaps` can have a `save()` method
too, which is helpful for the GUI...

Add common save method for Eta Omega maps

---

hexrd/imageseries/load/registry.py
hexrd/imageseries/save.py

Updated two files in imageseries package that used "is not" when it should be "!=". Unit tests still run, so this looks ok.

pep 8: is not vs. !=

---

hexrd/cli/fit_grains.py

`cli/fit_grains()` was using the same variable (`grains_filename`) to load the fit-grains estimate and write the fit-grains result.

Don't reuse grains_filename variable

---

hexrd/instrument.py

This adds rmat_c and tvec_c as optional arguments to angles_to_cart.
My specific use case is that, when I compute the bounding box for the
Laue widths, I first compute the box in angles and then use
angles_to_cart to convert to Cartesian.
If the crystal's position is not at the origin, we need to specify
tvec_c in order for this to work properly.

Allow specifying rmat_c and tvec_c in angles_to_cart

---

.github/workflows/container_build.sh
.github/workflows/package.yml

This PR moves the build of the package into a older Linux container. This ensure that we build with an old version of glibc so the package will work on older distros as well. @joelvbernier this should resolve the issue your collaborator is seeing.

Build package in container

---

hexrd/config/config.py
hexrd/config/root.py

To address this, I added a static method in the base config class that checks filename "correctness." If the filename is an absolute path, that is what gets used. If it is a relative path, then the working_dir is prepended. Finally, if a file exists for that path, then that is returned. Otherwise, IOError is raised.
I applied this to instrument config file and to the imageseries files loaded in the image_dict.

updated config to use working_dir consistently

---

hexrd/distortion/ge_41rt.py

Before, if a list was passed in, the params would remain as a list.
Using the setter ensures it is the correct shape and that it gets
converted to a numpy array.
This fixes cases where numpy array functions are called on the params.
This fixes the issue seen in #84 and in hexrd/hexrdgui#490
@joelvbernier @cjh1

Ensure GE_41RT params get converted to numpy array

---

hexrd/material.py
hexrd/unitcell.py
hexrd/valunits.py

This adds helper functions to save/load materials HDF5 files.
It also adds `dmin` properties so that the dependent values get
re-computed when the dmin is modified, both on the unit cell
and on the material.
It also uses valWUnit for unit conversions (Material uses angstrom,
while UnitCell uses nanometers).
These bugs were fixed:
1. "rhombohedral" should be "trigonal" for crystal system
2. The dmin that gets passed to getHKLs is now converted to the correct units
This also increased the default dmin to 1 angstrom, since less than this generates
a lot of values, and slows down the start of hexrdgui.

Add helper functions and a few fixes for Material class

---

hexrd/material.py
hexrd/mksupport.py

The commit messages are pasted below
1. Use isinstance(var, np.floating) for numpy floats
`np.float` is an alias to Python's `float` type, thus
`type(var) == np.float` does not return True for numpy float types.
However, `isinstance(var, np.floating)` will work. For instance:
```python
>>> a = np.float64(1)
>>> type(a) == np.float
False
>>> isinstance(a, np.floating)
True
```
If we want to also check for the Python float in addition to numpy float,
we can do:
```python
isinstance(var, (np.floating, float))
```
This change fixes an issue where U was being interpreted as a tensor, when
it was actually a single float.
2. Add Material function to update structure factor
We will call this when certain unit cell parameters are modified.

Fix U type check and add update_structure_factor() to Material

---

hexrd/WPPF.py

Multiple different type of input is now supported for initializing the `LeBail` class.
1. Passing spectrum data as `numpy.ndarray`, as a text file name or as a `Spectrum` class.
2. Passing params as a `dict`, a yaml file or a `Parameters` class.
3. Passing phases as a `dict`, a yaml file or a `LeBail_phases` class.
All options were tested with the example ceria dataset uploaded to the HEXRD google drive.

Wppf feature

---

hexrd/imageutil.py

It appears there was a bug injected as part of commit 55a797c0 (31-Jul-2020) for pep8 compliance. The PR changes the fast_snip1d() method back to calling signal.fftconvolve().

Fix signal.fft() call to signal.fftconvolve()

---

.github/workflows/container_build.sh
.github/workflows/package.yml
conda.recipe/meta.yaml
setup.py

It is required to use WPPF.
The version is set at 1.0.0 for reasons mentioned in hexrd/hexrd#99.
Fixes: #99
I think I might need to add it to the [meta.yaml](https://github.com/HEXRD/hexrd/blob/master/conda.recipe/meta.yaml) for conda as well.

Add lmfit to list of requirements for hexrd

---

hexrd/WPPF.py

This catches the `nan` values, and `<= 0.0` inside WPPF and sets the statistical weights for these points to `0`.
This fixes some non-convergence issues in `WPPF` with the Tardis and ceria dataset.

catch nans, zeros and negative values in WPPF

---

hexrd/material.py
hexrd/symbols.py

bugfix for HM symbol to space group number dictionary.
Some cif file e.g. from Springer have many different groups in same file. Modifications to account for that.

CIF read bug fix and improvements

---

hexrd/material.py

changed the `Materials` class to always have the first `hkl` not be excluded even if it lies outside `2\theta' range or can't satisfy Bragg's conditions.

Exclusion of first hkl is always False by default.

---

hexrd/WPPF.py

Previously, the angles were being divided by 10 in addition
to the lengths. The angles should not be modified for this conversion.

Don't modify angles for Angstrom -> nm conversion

---

hexrd/material.py

The logic was searching for the first dot. This does not work if the path has a dot in it for example a version number in the package.

Use pathlib to get suffix

---

hexrd/fitgrains.py

In some cases, presults may be empty for a specific detector. This would
lead to a numpy exception later when a vstack was attempted with an empty
list.
Check if presults is empty, and if so, set the culled results to empty as
well and continue.
@joelvbernier Is it reasonable for the `presults` variable to be empty? It looks like it is empty
sometimes for our 8-detector example, and that was causing the exception in https://github.com/HEXRD/hexrdgui/issues/643.
If it is not reasonable for `presults` to be empty, we may need to find a different fix.
Fixes: https://github.com/HEXRD/hexrdgui/issues/643

Check for empty presults before fitting attempt

---

.github/workflows/test.yml

pycifrw will not build with the latest version of XCode so downgrade to 11.7.

Switch to XCode 11.7

---

hexrd/unitcell.py

Rather than storing both the stiffness and compliance tensors, which
requires storing two tensors, and can run the risk of one being out of sync
with the other, make the compliance tensor a computed property.
This way, the only matrix that is stored is the stiffness tensor. If one
tries to get the compliance via `unitcell.compliance`, it will be computed
and returned. If one sets the compliance tensor via `unitcell.compliance = t`,
it will be converted to stiffness and stored as the stiffness tensor.
This simplifies some code in hexrdgui.

Make the compliance tensor a computed property

---

hexrd/unitcell.py

The stiffness is in GPa. Previously, the compliance was in GPa⁻¹.
Now, store and retrieve the compliance in TPa⁻¹ instead.
This can be done in hexrdgui instead, if you prefer to leave
compliance in GPa⁻¹ in hexrd.
Please double-check my math...

Store and retrieve compliance tensor in TPa⁻¹

---

hexrd/WPPF.py
hexrd/instrument.py

Added powder simulator to instrument class. Hooks to `WPPF.LeBail` are used to simulate. 
Required argument is list of `Material` objects. 
The parameters for the simulation can be changed using the optional `params` keyword. If this is not provided, then some sane default values are chosen.
The background is specified by an array or a filename with two rows of 2theta and background intensity. Finally, optional noise can be added via the `noise` keyword. Options to add `poisson`, `gaussian`, `salt and pepper` noise etc. have been added. Tested with MEC configuration and Zirconium crystal

Powder simulator

---

hexrd/findorientations.py
hexrd/fitgrains.py
hexrd/instrument.py

- added NaN removal and DC offset for maps in findorientations
- added exception handling for case of 0 simulated reflections in fitgrains
- fixed HDF5 string handling bug in `unwrap_dict_to_h5()`

hdf5 string error, and map normalization

---

hexrd/imageseries/process.py
hexrd/imageseries/save.py
hexrd/matrixutil.py

This has the following improvements:
1. Speeds up dark background subtraction (by about 2x)
2. Multi-thread when writing out the frame cache
3. Improve numba function speed with `cache` and `nogil`
For my archiving example with 4 detectors, and my 24 processor computer,
the amount of time it takes has gone from about 97 seconds to about 48 seconds.
The median computation runs for about the first 9 seconds, and that is only one
process per detector, so 4 processes. After the median finishes, each of the 4
detector processes runs 6 threads, and my CPUs all hang out at around 85%
usage until the end.
To use this: if other parallelism is going on, such as one process per detector, you should
limit the number of threads by passing the `max_workers` kwarg to `imageseries.write()`.
For instance, …

Archiving performance improvements

---

hexrd/constants.py

On Windows, checking if a file is writable via
`os.access(path, os.W_OK)` unfortunately does not work. We have
had to resort to a more brutish method of trying to open the file, like
this:
```python
def is_writable_file(path):
try:
with open(path, 'w'):
return True
except Exception:
return False
```
Unfortunately, just the act of opening a file with 'w' erases its
contents. We need to open with 'r+' instead to avoid this.
What the previous opening with 'w' resulted in:
1. Hexrd on Windows installed via a package would work correctly,
because the user running "hexrd" doesn't have permissions to write
to the file (since the package is installed with admin privileges).
2. Hexrd on Windows installed via conda/pip would cause a bug to occur,
because the user running "hexrd" does have …

Check if file is writable with 'r+' instead of 'w'

---

.github/workflows/test.yml
pyproject.toml
setup.py

The pyproject.toml file can be used to specify dependencies needed
for pip to run setup.py. Pip will create a virtual environment and
install these dependencies, then run setup.py.
This simplifies the development setup process so that instead of:
```python
pip install numpy
pip install -e hexrd
```
The developer can simply do:
```python
pip install -e hexrd
```
We need to include numpy in "install_reqs" now as well because
dependencies specified in pyproject.toml are only installed in the
virtual environment used to run setup.py, and numpy also needs to
be installed for use at runtime.
Fixes: #180

Add pyproject.toml for easier development installs

---

setup.py

It has the same issue as scikit-image.

Remove appdirs from install_requires for conda

---

hexrd/crystallography.py
hexrd/material.py

The structure factors were not getting filtered by exclusions after the exclusions were updated. This fixes it.
The `planeData.get_structFact()` subroutine now returns `planeData.__structFact[~planeData.exclusions]` in place of just `planeData.__structFact` .

return structure factors filtered by exclusions.

---

hexrd/material.py

The structure factor needs to be updated when plane data is created.
This helps fix some cases where new plane data was being created, but
the structure factor was not being updated, such as reported in
https://github.com/HEXRD/hexrdgui/issues/774#issuecomment-790179646.

Always update structure factor on new plane data

---

hexrd/unitcell.py

1. introduced `CalcOrbit` subroutine to calculate the equivalent points due to space group symmetry.
2. added `remove_duplicate_atoms` subroutine to remove duplicate atoms due to space group symmetry.
This is related to issue https://github.com/HEXRD/hexrdgui/issues/769

remove duplicate atoms

---

hexrd/material.py
hexrd/unitcell.py

fixing error introduced in last push to materials. A full 6 parameter list was being passed to `~rqpDict[self.unitcell.latticeType][1]` instead of the reduced set. This is a fix for issue #212 
Fixes: #212

Material fix

---

hexrd/material.py

Because PlaneData objects have immutable HKLs, when something happens that causes the HKLs to change (such as a change in dmin or sgnum) , a new PlaneData object must be instantiated with the new HKLs.
This PR does two main things:
1. Skips creating a new PlaneData object if the HKLs match. So small dmin changes, for instance, won't create a new PlaneData object.
2. Copies over old PlaneData attributes to the new PlaneData, including exclusions.
The exclusions are copied over by creating a mapping between the old HKLs and the new HKLs, and using this to set the new exclusions based on the old ones.
You can see the exclusions persisting here in hexrdgui:
Notably as well, other attributes such as the tThWidth and tThMax get preserved when a new PlaneData object is created also.
This, along …

Copy old PlaneData attributes to new PlaneData

---

hexrd/material.py

avoid initializing planedata if hkls don't change. update structure factors regardless.

using _hkls_changed() instead of _newPData()

---

hexrd/crystallography.py
hexrd/material.py

Previously, the Laue group wasn't getting updated, and this was causing
incorrect d-spacings and two theta to come out.
Update the Laue group when it is modified.
The reason this was causing issues is because, as of #204, when a new PlaneData object is created,
its properties are [copied from the old PlaneData object](https://github.com/HEXRD/hexrd/blob/b0d51d52c40002aa8bf1d18938c441e3adacda93/hexrd/material.py#L255), in
order to preserve things like `tThMax` and `tThWidth`. However, the `laueGroup` is also copied over,
which means that if we don't update the `laueGroup` on the original `PlaneData` object, the new `PlaneData`
will have an incorrect `laueGroup`. Thus, we need to update it.

Update Laue group on PlaneData when modified

---

hexrd/instrument.py

Threading was attempted, but it appeared that all the threads would
either be fighting for the GIL or fighting for the compiler lock in
numba. Threading actually resulted in a large slowdown.
Multiprocessing seems to work well, since there is not a lot of
data to transmit back and forth. For 2048 rows by 2048 columns
and pixel sizes of 0.2, I was able to go from about 46 seconds
to about 6.8 seconds for running this property.

Perform multiprocessing on pixel_solid_angles

---

hexrd/crystallography.py
hexrd/material.py

When the Laue group changes, the lattice parameters may be incompatible,
and cause an error in PlaneData.__calc().
This commit adds a function to allow us to update both the Laue group
and lattice parameters simultaneously to avoid this issue.
Fixes: hexrd/hexrdgui#821

Update PlaneData laue and lparms simultaneously

---

hexrd/symmetry.py
hexrd/utils/decorators.py

Profiling hexrdgui indicated that the most time consuming function
on hexrdgui startup is hexrd.symmetry.isnew. Adding a numba
decorator provides a 20-40% speed-up for starting hexrdgui when
using numba.
This commit also adds and uses a decorator in hexrd.utils.decorators
called "numba_njit_if_available". Basically, if we are using numba,
it forwards the decorator arguments to numba.njit. And if we are not
using numba, it does nothing.
If we want to improve hexrdgui start-up time in the future, profiling
indicates that these are the next most time consuming functions (in
order):
```python
hexrd.unitcell.unitcell.CalcLength
hexrd.matrixutil.findDuplicateVectors
hexrd.unitcell.unitcell.CalcStar
```

Use numba, if possible, in hexrd.symmetry.isnew

---

hexrd/material.py

If `dmin` specified by keyword, then use that value. 
Otherwise set it to default and check if value is available in the file. If a value if available, then replace the default value with that.

fix logic of setting dmin during materials init. 

---

hexrd/instrument.py

Finished the HDF5 I/O for the HEDMInstrument class.  Now the `__init__` will identify the `instrument_config` kwarg as either an HDF5 File object, or a dict (_i.e._, coming from the existing yaml-style config).  Similarly, `HEDMInstrument.write_config` now takes a `style` kwarg that can be either 'yaml' or 'hdf5'.  Note that in the case of the 'yaml' style (still default), array-like panel buffers get clobbered (always the limitation with a standalone yaml file).  Also, in cases where a `panel_buffer` is `None`, it is substituted with `[0., 0.]` in the 'hdf5' format.
I forsee the HDF5 format superseding the yaml format soon...

Instrument updates

---

conda.recipe/meta.yaml

Since [this import was removed](https://github.com/HEXRD/hexrd/blob/c19aaaf5e0ad6660475b13aad2b8f98424faf64a/hexrd/cli/__init__.py#L11), the entrypoint needed updating.
This now matches the [entrypoint in setup.py](https://github.com/HEXRD/hexrd/blob/c19aaaf5e0ad6660475b13aad2b8f98424faf64a/setup.py#L81), so should hopefully work.

Update entrypoint for conda

---

hexrd/instrument.py

When an instrument config is loaded from an HDF5 file, the panel buffers
will be numpy arrays. Allow panel buffers of length 2 in the
HEDMInstrument.__init__ method.

Allow numpy array panel buffers of length 2

---

hexrd/instrument.py
hexrd/transforms/xfcapi.py

Added the following methods to `instrument.PlanarDetector`:
```
pixel_tth_gradient(origin=[0., 0., 0.])
pixel_eta_gradient(origin=[0., 0., 0.])
```
which return |&nabla;2&theta;| and |&nabla;&eta;|, respectively.  The `origin` kwarg is handed to `PlanarDetector.pixel_angles()`.  Logic for handling the &eta; branch cut is included.  Results for the default instrument shown below

added pixel angle gradients

---

hexrd/instrument.py
hexrd/utils/decorators.py
tests/test_memoize.py

Two parts to this PR:
1. Update memoize decorator and add tests
This memoize decorator will now work for arguments with most built-in
python types, includings lists and dicts, and it will now also work
for numpy arrays as well.
Some tests were added to demonstrate its functionality.
2. Memoize the pixel_angles function
This is a pattern we can repeat for other functions we want to memoize
as well: the function body was moved to the module level, all arguments
are passed to it, and the `@memoize` decorator from hexrd.utils.decorators
was used on it.
This results in pixel_angles() only needing to be computed once if the
same arguments are used in the future. If different arguments are used,
it will be re-computed.
One caveat: memoization is not transferred to other processes in …

Memoize the pixel_angles function

---

hexrd/distortion/dexela_2923.py
hexrd/distortion/ge_41rt.py
hexrd/gridutil.py
hexrd/indexer.py
hexrd/instrument.py
hexrd/transforms/xf.py
hexrd/xrdutil.py

Using "njit" instead of "jit" means to use the "nopython" argument,
which can be faster. But it may not be allowed for some function
argument types.
Caching will get numba to cache the functions it compiles so that it
does not have to compile them again. This can provide a big speed-up
after the functions have been called once and saved.
Note that if you edit the file that contains the function, the cache
will automatically be re-generated the next time it is ran.
nogil tells numba to release the GIL. This is helpful in case the
function is used in any python multi-threading.
Caching is also helpful if the function is used in any python
multi-threading because numba can only compile on one thread at a time...
In any case, these changes all have the potential to be good, but we should …

Use numba.njit(cache=True, nogil=True) for all

---

tests/test_material.py

This is just adding a little framework for testing the Material class,
through which we can add more tests.
For: #214

Add some basic testing for the Material class

---

hexrd/config/instrument.py
hexrd/config/root.py
hexrd/instrument.py
hexrd/utils/concurrent.py
hexrd/utils/decorators.py
tests/test_concurrent.py

Before, the multi-threading was a little too fine-grained, and the main thread was running a lot of code that the threads could have been running. Now, it's a little more coarse-grained, and a fair amount of time is being spent in the threads other than the main thread.
This resulted in nearly a 2x speed-up for the GE example.
Multiprocessing was attempted as well, but pickling and unpickling image series seems to be expensive, and makes it slow. Perhaps it's something we can pursue if we find a faster way to pickle/unpickle image series data.

Eta omega map generation speedup

---

hexrd/crystallography.py

When the wavelength is set on the PlaneData object, do not re-compute
if the wavelength is the same.
Note that this checks for similarity with an absolute tolerance of `1.e-8` and a relative tolerance of `1.e-5`.

Do not re-compute PlaneData if wavelength is same

---

hexrd/xrdutil/nf-hedm/nf-HEDM_test.py

This is a less naive implementation. That doesn't ship around a bunch of data. It basically partitions the coordinates across the ranks and then uses multiprocessing on each rank ( rather than multiple MPI processes per rank ). The image stack is loading and dilated on each rank to avoid have to ship it around. By making the MPI calls ourselves we can also take advantage of direct memory access to numpy arrays, so removes the overhead of pickling.
Note: If we go down this route we still need to work out what todo with the controller, currently progress monitoring is a little confusing with multiple ranks!

WIP: Simple MPI implementation using gather

---

.github/workflows/package.yml
conda.recipe/meta.yaml

Downgrade scikit-learn to try Windows package fix

---

hexrd/config/material.py
hexrd/findorientations.py

There was an oversight where the call to `clean_maps` to enable feature detection was modifying the underlying object and removing NaNs, which are critical for indexing cases where the detectors have gaps in eta coverage.

filter copy of maps instead of main object

---

.github/workflows/package.yml

Before this commit, if we re-run the GitHub actions workflow (which may
be done if a workflow failed for a network issue, for instance), the
workflow will fail when it tries to upload the anaconda package because
the anaconda package already exists on anaconda.
Force the upload so that this error does not happen, and so that the
packages on anaconda are generated from the latest workflow that was ran.

Force upload packages to anaconda

---

hexrd/instrument.py

computes the lorentz polarization factor for any 2D planar detector given the fraction of horizontal and vertical polarizations of the incident x-ray. 
Note that the factors **aren't** properties of the `PlanarDetector` class since it requires the inputs of the polarization fractions. 
The computed factors for a typical MEC configuration gives reasonable results shown below.

Lorentz Polarization factor for 2D detectors

---

hexrd/material.py

@saransh and I spoke about this. We agreed that the previous behavior
should be restored, so that exclusions do not get changed when
material properties get modified (such as is done sometimes with WPPF,
or when the user modified material settings in the GUI).
He will also track down and fix the specific issue he was encountering
that caused him to submit #253.

Revert #253

---

hexrd/instrument.py
hexrd/material.py
hexrd/utils/compatibility.py

In h5py >= 3.0.0, h5py no longer automatically converts to string
data types, but always leaves string/byte data as bytes. Thus, we
need to add some compatibility to automatically convert to strings
when the underlying data is a string.
This fixes two specific cases that I currently know of: #273 and
loading in a distortion string in an instrument hdf5 file.
We should add this in more places if I missed any.
Fixes loading [this HDF5 instrument file](https://github.com/HEXRD/hexrd/files/6736675/ge.hexrd.zip).
Fixes: #273

Convert to strings for h5py string types

---

hexrd/material.py

Rather than enabling all hkls with two theta less than 90 degrees
by default, we are now enabling the first five hkls by default.
This adds two utility functions, though, for automatically enabling
hkls: one for enabling all hkls below an index, and one for enabling
all hkls below a two theta value (which is copied from the previous
`set_default_exclusions()` function).
The first utility function gets called by default, which enables
only the first five hkls.
Fixes: #225

Enable the first five hkls by default

---

scripts/convert_instrument_config.py

The legacy conversion script to take old hexrd 0.5.x-style instrument config files to the current (>=v0.6) format was out of date.  A user (@hsheng94) had an example of a legacy instrument file from CHESS (closes HEXRD/hexrdgui#987).  This adds the new conversion script, which includes a CLI.

updated legacy instrument config conversion

---

hexrd/instrument.py

The intensities in the image after the solid angle correction was applied grew very large. This was because the correction factors were small numbers and division by these numbers led to very large values. This PR rescales solid angle correction to range [1, infinity] and avoids that. Now the corrections together with the Lorentz polarization correction, agrees very well with Dave McGonegle's Matlab code.

Rescale pixel solid angle correction.

---

hexrd/fitgrains.py
hexrd/instrument.py

The previous `save_spot_list` argument was intended to be used for
this purpose, but it was unused.
This was renamed to `return_spot_list` to emphasize that the spot
list will be returned (rather than some other form of saving such
as writing to disk). And now, if `return_spot_list` is `True`, all of
the data that is normally written out to the HDF5 file will be appended
to the output.
This data will be used for spot montages.

Use option to return spot data from pull_spots()

---

hexrd/material.py

ability to charge as part of _set_atomdata function in Material class. This will be utilized for PR https://github.com/HEXRD/hexrdgui/pull/973 in the GUI.

pass charge value to _set_atomdata.

---

.github/workflows/container_build.sh
conda.recipe/meta.yaml

Lately, the Linux packaging has been using python 3.9. Python 3.9 may
work, but hexrdgui is currently fixed to python 3.8. Fix python to 3.8
for the Linux packaging as well until we decide to upgrade python in
both hexrd and hexrdgui simultaneously.

Fix python=3.8 for Linux packaging

---

hexrd/material.py

Check if `dmin` and `Kev` are floats and convert them to `valunits` in the `herd.material.load_materials_hdf5` function. 
It is assumed that `dmin` is in Angstrom and `Kev` is in kilo ev. This fixes #154.

dmin and kev float conversion in load_materials_hdf5

---

.github/workflows/container_build.sh
.github/workflows/package.yml
README.md
conda.recipe/meta.yaml

This is an attempt to use the `conda-forge` channel instead of the
`defaults` and `anaconda` channels, for all packages.
This will hopefully fix the issue where we had to downgrade scikit-learn
because it would fail to install on Github Actions on Windows. This will
hopefully also fix a current issue for the Windows packaging where
the llvmlite dll cannot be loaded by numba. It makes more sense for us
to install these packages from conda-forge since the respective project
developers actually maintain the packages on conda-forge (whereas their
packages on the anaconda/defaults channels are maintained by anaconda).
We will first need to make sure the packaging and tests pass, and then
move on to test the packages manually.
If we run into crashing issues on Mac with openblas, as we have in …

Use conda-forge instead of anaconda channels

---

hexrd/imageseries/stats.py
hexrd/imageseries/tests/common.py
hexrd/imageseries/tests/test_stats.py

This addresses Issue #306. For percentile_iter and median_iter, a buffer is created to store as many frames as possible so as to avoid repeated imageseries frame copies in stats._toarray(). The size of the buffer is half of available memory when the stats module is loaded. 
Additionally,
* This fixes a bug in the percentile iterator that duplicates a row between chunks. It did not affect the result, but performed unnecessary computations.
* Unit tests were improved: old ones strengthened and new ones added.

Imageseries stats

---

hexrd/findorientations.py

The "filter_maps" argument was not being converted during string
formatting, and this was raising an exception.
It doesn't really need to be there anyways, since the logging
statement implies that "filter_maps" is `True`.

Fix logger error for filtering eta omega maps

---

hexrd/imageseries/process.py

From the [pickle documentation:](https://docs.python.org/3.8/library/pickle.html#what-can-be-pickled-and-unpickled)
```
Similarly, when class instances are pickled, their class’s code and data
are not pickled along with them. Only the instance data are pickled.
```
Class data does not get pickled, and the class's `__init__()` method
also does not get called when the object is unpickled. This causes
the `_opdict` class variable in `ProcessedImageSeries` to be empty
when it gets pickled and unpickled [here](https://github.com/HEXRD/hexrd/blob/408bea18f11f3ad968bbefa64518f530bf0882dd/hexrd/fitgrains.py#L83) for when
multiprocessing uses spawning rather than forking (and python 3.8
defaults to use forking only on Linux).
Thus, to make sure the `_opdict` gets pickled as well, we can make it
a …

Fix pickling for ProcessedImageSeries

---

hexrd/material.py
hexrd/unitcell.py

cif import was not using the charge information for each atomic species. This was raising some errors in the import. This has been fixed.
Additionally, it is checked if the scattering factors for charged species is present in the `herd.constants.scatfac` dictionary. If its not present, then the neutral atom scattering factors is used by default. This was introduced because the test case has `Te2-` which is not present in the international tables.

Fix charge species import in cif

---

setup.py

Previously, if a conda development environment was set up, when
the `... pip install -e hexrd ...` was performed, the hexrd
version would come out as `0.0.0`.
Ensure setuptools_scm is present so that a correct version is
displayed in development environments.

Ensure setuptools_scm is present for conda dev version

---

hexrd/imageseries/stats.py

Previously, if integer data (such as `uint16`) was input to the
`average()` and `average_iter()` functions, it could overflow during
the summation.
Now, convert it to float32 at the beginning instead of the end to prevent
overflow from happening.

Convert to float before average to avoid overflow

---

hexrd/crystallography.py

Calculates powder intensity. the property `planeData.powder_intensity` has the data filtered by exclusions. The full data is present in `planeData._powder_intensity`. This relates to issue https://github.com/HEXRD/hexrdgui/issues/1042

powder intensity in planedata.

---

hexrd/material.py

Check for cases where occupancy or the Debye Waller factors are present but undefined, most notably by a "?".
The update looks for strings and populates them with default values of 1.0 and 1/2sqrt(2)pi.

Fix cases when the occupancy or the isotropic Debye waller factors are undefined

---

hexrd/wppf/wppfsupport.py

This is so that no bad profiles are generated when angular range of data is very small. Usually <5 degrees. This will fix issue https://github.com/HEXRD/hexrdgui/issues/1026

change default values and lower bounds for HL and SL values.

---

hexrd/instrument.py

Overdue swap to the smoother pixel gradient arrays instead of the old `xrdutil.angularPixelSize` method, which was a bit janky.

swith to using pixel angular gradient arrays

---

hexrd/wppf/peakfunctions.py

Minor adjustment in the `peakfunction.calcrwp` function. The weighted sum of squares had a small inaccuracy.

slight modification to the rwp function.

---

hexrd/material.py

Catching a case when the element is **_not_** specified as `El+ / +El` or `El- / -El`

when none of the charge state is present in the element description.

---

.github/workflows/package.yml
hexrd/instrument.py

There is an edge case check that simulated reflections passed through `xrdutil._project_on_detector_plane` are verified to intersect the detector frame.  Previously, the results were always filtered by the (typically) trivial boolean vector returned.  Array data was copied as well.  Now it only performs filtering if `np.any(~on_plane)` is `False`.

minor tweak to filtering

---

hexrd/imageseries/load/imagefiles.py
hexrd/xrdutil/utils.py

List is perhaps long overdue; not sure why we decided to punt on it earlier, but it seems to be the only way to reliably allow the use of glob strings (which is useful!) in the `image-files` adapter for `hexrd.imageseries.load`.

Added list sort to deal with glob

---

pyproject.toml
setup.py

The latest version of numba (0.54.1) requires numpy to be < 1.21. The
latest version of numpy is 1.22, however.
Thus, for both the build environment and the run environment, we need
to downgrade numpy to 1.20, so that it is compatible with numba. Fixing
the version is needed for pip dev environments, because pip is not smart
enough to downgrade numpy for us. Conda, however, does downgrade the numpy
version automatically, which is why we aren't running into the issue with
conda environments.
This should fix the errors occurring on hexrdgui master.
Note: it looks like numba 0.55 is supposed to come out soon, which will
require numpy < 1.22.

Pin numpy to version 1.20

---

pyproject.toml
setup.py

We need numpy<1.21 for the latest numba to work.
Loosening up the restriction from numpy==1.20 to numpy<1.21 fixes an
issue with conda dev environments where numpy being 1.20.3 would not
match perfectly, and produce an error.

Change numpy==1.20 to numpy<1.21

---

hexrd/instrument.py

It appear's that skimage's `regionprops` followed by `weighted_centroid`
is much faster than scipy's `center_of_mass` for `pull_spots()`.
In one example I had, using `skimage` brought the total time for
`pull_spots()` down from 55.2 seconds to 31.6 seconds (where
skimage took 1.4 seconds compared to scipy's 23.8 seconds).
We should make sure that our results are identical before merging, and
that skimage can handle all cases the same way that scipy did.

Use skimage for center of mass instead of scipy

---

conda.recipe/meta.yaml

The build step of hexrd was using numpy 1.22, because it is the latest.
However, at runtime, numpy 1.20 would be installed because it is the
latest version that numba supports.
The mismatch in version caused an error containing the following:
```python
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
```
Fix the versions of numpy to 1.20 so they will both match. We can bump
the numpy version when numba supports newer versions.

Fix conda numpy version to 1.20

---

conda.recipe/meta.yaml

I believe that the strict constraint is causing some issues with installing
the latest hexrd pre-release.

Try fuzzy constraint for numpy version

---

hexrd/findorientations.py
hexrd/fitting/calibration.py
hexrd/instrument.py
hexrd/rotations.py

In the event a cluster has exactly 2 points, there was an error in computing the average quaternion.  This has been fixed.

addresses case where cluster has 2 orientations

---

hexrd/material.py

The function is present in `material.Material.compute_powder_overlay`. The inputs are `ttharray` which has the two theta coordinates from the polar view, `fwhm` which is the full width half maxima of the powder peaks in degrees and `scale` which scales the peaks by a constant factor. Important to note that there could be a DC offset which can make the plot not look great. That can ideally also be estimated if the azimuthal integration is passed. This will fix https://github.com/HEXRD/hexrdgui/issues/1002

Simulated peak

---

hexrd/material.py
hexrd/unitcell.py

The absorption length is calculated based on the theoretical density, X-ray energy and atom info of the unit cell.  The property is `Material.absorption_length` and the value returned is in microns.
Tested for a few test cases and matched with the data available from https://henke.lbl.gov/optical_constants/atten2.html

routines to get absorption length of a material

---

hexrd/imageseries/load/__init__.py
hexrd/imageseries/load/rawimage.py

This creates an imageseries adapter for custom file formats (`raw-image` keyword). 
You can create an instance like this:
```ims = imageseries.open(filename, "raw-image")```
The input file is a YAML file describing the scalar data format and basic properties of the images. Here is an example:
```
#
#
#
filename: RUBY_4537.ge
shape: 2048 2048
skip: 8192
scalar:
type: i
bytes: 2
signed: false
endian: little
```

Raw image imageseries

---

hexrd/material.py

If the `tThWidth` wasn't in the HDF5 file, then the default was being
set to `np.radians(Material.DFLT_TTH)`. However, `Material.DFLT_TTH`
was already in radians.
This would result in the default two theta widths in HexrdGui being
0.004° instead of 0.25°.
Fix this so that the conversion to radians only occurs if the two theta
width is loaded from the HDF5 file.

Fix default material tThWidth for HDF5

---

hexrd/material.py
hexrd/unitcell.py

The main function to call is `Material.remove_duplicate_atoms`. This function will call the `unitcell.remove_duplicate_atoms` function and update `Material.planeData` after the `unitcell` class is updated. 
Some logic fixes to the `unitcell.remove_duplicate_atoms` function. Instead of returning the sites, the function now updates the `unitcell` class.

Remove duplicate atom fix

---

hexrd/material.py

check if tThWidth is present in planeData before trying to convert to degrees. This was leading to an error during state write.

Fixing write error in material

---

hexrd/constants.py
hexrd/instrument.py

We need to force the multiprocessing context to 'fork' on platforms (not Windows) where it is available.

Fix multiprocessing context for ProcessPoolExecutor

---

conda.recipe/meta.yaml
setup.py

The updated calibration package uses this for a status bar, and we should probably use `tqdm` across the code base to report status in loops.  @psavery -- would be great to figure out how to use it to talk to status bars in the GUI.

add tqdm package dependency

---

hexrd/constants.py
hexrd/fitting/calibration.py
hexrd/fitting/fitpeak.py
hexrd/fitting/peakfunctions.py
hexrd/fitting/spectrum.py
hexrd/fitting/utils.py
hexrd/instrument.py

Adding a new 1-d spectrum fitting module for calibration that uses `lmfit`; this was really precipitated by the need to get the DCS pink beam function working.  Constraints are essential.  That use case is passing basic testing, but need to do several things:
@saransh13 and @darrencpagan -- I am open to any ideas you have regarding enhancing the initial parameter estimation.  What we currently have is _ok_, but might not be robust if the initial guess is a bit further off.  I am aware that there very well may not be a better generic rubric, but I figured I would plant the seed.

Fitting fixes jvb

---

hexrd/instrument.py

This address https://github.com/HEXRD/hexrdgui/issues/1161; now if a `panel_buffer` attribute is `None`, no exception is encoutnered.  However the HDF5 format (.hexrd) config gets written with `panel_buffer = [0., 0.]` instead of omitting it.  I think we should alter that behavior to just omit, which gets caught in the `HEDMInstrument.__init__`.

catch None in hdf5 write as TypeError

---

hexrd/fitting/calibration.py
hexrd/instrument.py

The fitting will fail as currently implemented if the patch/spectrum data is all zeros or otherwise has no discernible peak.  Can you test this for your failing cases @psavery?  Satisfies one of the tasks in #404.

Catch for flat patch data

---

.github/workflows/package.yml

Within the past few weeks, `windows-latest` was changed to point to
`windows-2022` instead of `windows-2019`. Our Windows packaging has
had errors since that transition.
It would be preferable to fix the issues with `windows-2022` so that
we can use it. However, the error messages are cryptic (pasted below).
We can downgrade to `windows-2019` until we find a fix.
```python
error: command 'cl.exe' failed: None
Traceback (most recent call last):
File "C:\Miniconda\envs\hexrd\Scripts\conda-build-script.py", line 10, in <module>
sys.exit(main())
File "C:\Miniconda\envs\hexrd\lib\site-packages\conda_build\cli\main_build.py", line 488, in main
execute(sys.argv[1:])
File "C:\Miniconda\envs\hexrd\lib\site-packages\conda_build\cli\main_build.py", line 477, in execute
outputs = …
```

Downgrade windows CI to windows-2019

---

hexrd/findorientations.py
hexrd/instrument.py
hexrd/rotations.py

Currently, the η-ω map generation could not handle multi-wedge imageseries.  This PR addresses that shortcoming.  There are a few tacit assumptions about the imageseries, however:
1. the wedges must be non-overlapping
2. the wedges must not exceed 360º
3. the wedges, and thus frame order, must be monotonically increasing in ω
I will attach a test case form a DAC experiment.

added logic to handle omega gaps

---

hexrd/config/imageseries.py
hexrd/config/root.py
hexrd/constants.py
hexrd/fitgrains.py
hexrd/imageseries/process.py
hexrd/instrument.py

Finally adding the ability to specify ROI in a detector.  The usage is that any imageseries with an unspecified detector panel will be treated as "shared", and the detectors not represented in an image dictionary input will use the ROI to grab its pixel data.  The obvious application is for multi element detectors.  Closes #419. 
- requires explicitly passing a list of detectors over which to share

add roi handling

---

hexrd/crystallography.py

Added new utility methods for
1. converting hexagonal Miller direction indices to cartesian components in the crystal frame.
2. converting hexagonal Miller direction indices to Miller-Bravais.
3. converting hexagonal Miller-Bravais direction indices to Miller.
Note that the older function `millerBravaisDirectionToVector` is superceded by `convert_Miller_direction_to_cartesian`

added new Miller-Bravais direction utils

---

hexrd/instrument.py

When multiple grains were being exported simultaneously due to
multiprocessing the `pull_spots()` function, a race condition would
cause an error with this body of code:
```python
if not os.path.exists(output_dir):
os.makedirs(output_dir)
```
Basically, two processes would both see at the same time that the
output directory does not exist, and then they would both try to
make it at the same time. One process would make the directory,
however, and then the second process would get a `FileExistsError`
because the directory was already created.
To avoid the race condition, just modify the code to this:
```python
os.makedirs(output_dir, exist_ok=True)
```
This appears to fix the issue in my testing.
Fixes: hexrd/hexrdgui#1192

Fix spot export error for multiple grains

---

hexrd/material.py

For the dmin argument, `Material.__init__()` treats `None` and
`Material.DFLT_DMIN` differently. If it is `None`, then the dmin is read
from the HDF5 file if available. However, if it is not `None`, as was
the case before, then the dmin will not be read from the HDF5 file.
Default it to `None` in `load_materials_hdf5()` so that it will be read
from the HDF5 file.
Fixes: hexrd/hexrdgui#1186

Set default dmin to None in load_materials_hdf5()

---

hexrd/imageseries/process.py

This performs a gaussian laplace filter on the data.
Note that in my testing of this, it seems to be a time-consuming
operation to perform.
Fixes: #43

Add a gaussian laplace op to ProcessedImageSeries

---

hexrd/constants.py
hexrd/symmetry.py

fractional coordinates of 0 and 1 are the same; `numpy.modf` was not handling it properly. Added additional handling. Fixes density of ruby. All other densities are also consistent.
Tested with GUI

density fix for ruby

---

hexrd/material.py
hexrd/mksupport.py

Changing behavior of material load. the beam energy is written to the h5 file now. changes summarized below:
1. If values for `dmin` and `kev` are passed, then they supersede values in the file or the default values.
2. If values are not passed, then file is checked for values of `dmin` and `kev`. If found, then these values are used.
3. If nothing is passed and values not present in file, then the default values are used.
Tested with GUI, with both old material files and new ones (with kev)

Material load

---

hexrd/fitting/calibration.py
hexrd/instrument.py
hexrd/valunits.py

A recent merge broke the ability to use `instrument.HEDMInstrument.extract_line_positions()` with array-like input for the `plane_data` arg.  This PR restores that functionality.  Some default values are also updated, noting that the 2theta tolerance is now in % difference, not absolute deg.
closes #441

restore functionality with array-like tth input

---

hexrd/unitcell.py
hexrd/wppf/phase.py

The defunct `unitcell.CalcAnomalous()` function was being called inside `unitcell.remove_duplicate_atoms()`. This PR removes that call. Additionally, `wppf/phase.py` was referencing `unitcell.f1` and `unitcell.f2` variables, which got defunct with `unitcell.CalcAnomalous()`. Those references are removed too. 
The broken `unitcell.calc_absorption_length()` function was fixed as well.
Tested with GUI and command line.

Unitcell fixes

---

pyproject.toml
setup.py

The latest numba supports numpy 1.22, so allow that version.
When numba releases 0.56.1, numpy 1.23 will be supported as well.

Bump pinned numpy version to 1.22

---

hexrd/instrument.py

The use of `np.unique` is replaced with hexrd's `uniqueVectors` with a tolerance of 1e-6 to avoid an overly strict condition in the presence of roundoff errors.
This should fix your issue @darrencpagan

multiwedge tolerance fix on delta omega

---

tests/find_orientations_testing.py

These can be different but the eta omega maps can still match if one
of the plane data objects was instantiated with an explicit list of hkls.
This also adds a comparison to ensure that the omegas match.

Remove hkl_indices comparison from testing

---

hexrd/fitting/utils.py

Enhance parameter name matching to take wildcards.

Update spectrum fitting utils to support wildcards in parameter name matching

---

.github/workflows/test.yml

If we try install the latest the binary wheel is not available and we run into build problem trying to build locally.

Pin fabio to 0.12 on the Mac

---

hexrd/material.py

Was messing up a case with positive ions in the crystal.

replacing "if" with "elif" in line 604 of materials.py. 

---

.github/workflows/test.yml
hexrd/imageseries/save.py

When writing out the [multiruby dexelas](https://github.com/HEXRD/examples/tree/master/NIST_ruby/multiruby_dexelas) example imageseries in hexrdgui after
performing aggregation, I would encounter the following error:
```
TypeError: No conversion path for dtype: dtype('<U3')
```
It appears that some of the metadata being saved as HDF5 attributes
was a unicode string. Specifically, for this case, it appears that the
`panel_id` key had a unicode `ff1` value.
Converting to a regular string fixes the issue.
I don't know why the panel ID came out to have a unicode value, but
we can guard against it and convert it into a regular string.

Guard against unicode when saving HDF5 imageseries

---

hexrd/config/findorientations.py
hexrd/crystallography.py
hexrd/findorientations.py
hexrd/indexer.py
hexrd/instrument.py
hexrd/xrdutil/utils.py

This closes #452 and cleans up the yaml config for far-field HEDM.
We will probably have to make accompanying changes in `hexrdgui` as well @psavery...
Fixes: #188

changed hkl specification for indexing to master hklID

---

hexrd/xrdutil/phutil.py

The `source_distance` is on the instrument now.

API change to tth_corr_map_sample_layer

---

hexrd/unitcell.py

As the title says. Previously only reciprocal and direct space were supported.

Add calculating symmetric vectors in cartesian space.

---

hexrd/imageseries/load/hdf5.py

Previously, the HDF5 adapter was tacitly assuming the HDF5 dataset specified was 3-d; this automatically handles the case of 2-d data by stacking a 2-d array in the zeroth (left-most) axis and raises an exception if the specified dataset is neither 2-d or 3-d.

Added ability to import HDF5 imageseries with 2-d data

---

hexrd/wppf/WPPF.py
hexrd/wppf/phase.py
hexrd/wppf/xtal.py

Fixing issue https://github.com/HEXRD/hexrdgui/issues/1296
1. Always convert wavelength to nm.
2. Modify the polarization factor for transmission geometry
3. Remove normalization of structure factor for best Rietveld results.

WPPF -- Rietveld fixes

---

hexrd/wppf/RietveldHEDM.py

As the title says. Fixes issue #480 
Fixes: #480

add missing colon.

---

hexrd/grainmap/nfutil.py
scripts/process_nf.py

Fixed chunking with no leftovers

Nf chunking

---

hexrd/resources/tardis_reference_config.yml

Updated the separation of image plates 2 & 4 (bottom and top) to 23.13mm as per Jon Eggert's notes for TARDIS-C2.

modified Y translations in accordance with JHE's TBSep=23.13mm

---

hexrd/rotations.py

I ran into a case really close (angle was within ~2e-8 of pi) to a binary rotation that was not triggering the special axis calculation in `rotations.angleAxisOfRotMat`.  I adjusted the tolerance, but it could use a closer look @donald-e-boyce.
Two questions:
1. is the case of small angle sufficiently handled so as not to clobber rotations for which the axis is still calculable?
2. is the tolerance of 1e-6 the best choice for detecting the binary rotation?  Using 1e-8 wasn't quite working...
We really need unit tests for the rotations module...

tolerancing for detecting binary rotation was failing

---

hexrd/crystallography.py
hexrd/xrdutil/utils.py

The polar view output format from `hexrdgui` has angles for the 2θ and η coordinates; had to update `SphericalView.warp_polar_image` to be compatible.

angle units change

---

hexrd/material.py
hexrd/unitcell.py

As the title says. Ignores `f'`, `f"`, `fNT` and `frel` for atoms with Z > 92. Came up during analysis of alpha-Pu.

Ignore anomalous scattering factors for Z > 92

---

hexrd/utils/decorators.py
hexrd/xrdutil/phutil.py
scripts/pinhole_2theta.py

This follows [`calc_twotheta_pinhole()`](https://github.com/HEXRD/hexrd/blob/cb7bbaa341d07596754f3b55435f17654f89e288/scripts/pinhole_2theta.py#L176), but assembles the inputs from the hexrd classes.
~~Once we have two versions of this function: one that takes arbitrary xys and calculates the tth distortion for them, and one that outputs a tth distortion correlation map for all detector pixels, it will be easy to integrate into hexrdgui.~~
~~The function is not complete - we do not yet have the pixel positions in spherical coordinates.~~
~~This function is now working, but the results are not correct. We need to review the inputs to ensure they are being converted properly.~~
This now appears to be working exactly as it should!
The only thing left is to look into improving performance, …

Add Rygg pinhole to phutil

---

hexrd/cli/fit_grains.py
hexrd/config/__init__.py
hexrd/config/material.py
hexrd/crystallography.py
hexrd/fitgrains.py

This fixes #512 . 
Changes include:
- A new `exclude()` method in PlaneData for selection of HKLs using min/max cutoff values for d-spacing, two theta, structure factor and powder intensity. See  [test_exclude.py](https://github.com/HEXRD/hexrd/files/11314214/test_exclude.py.txt) for a script for testing the exclude() method. I used the ruby material in the single_GE example.
- A simple fix for a problem in handling multiple configuration files (each subsequent config was merged with the first instead of being merged with the previous, as described; and the `save() `function was out of date.)
- Setting plane data exclusions in `cli.fit_grains` before the main fitting method is called instead of in `hexrd.fitgrains` inside the main fitting method. This was the main problem because it reset …

fixing HKL reset problem in fitgrains

---

hexrd/instrument/hedm_instrument.py

We can catch this exception in HEXRDGUI, and this will prevent us having to check the buffer shape every time, as is done in hexrd/hexrdgui#1419.

Add specific exception for buffer mismatch

---

hexrd/xrdutil/utils.py

If you start a program by running `from hexrd import material`, this triggers
a circular import, because the material ends up triggering an import of the
instrument, which triggers an import of `hexrd.material` again.
Do not import the instrument in `xrdutils`. Let's keep it simple. This fixes
the circular import.

Fix material circular import

---

hexrd/instrument/detector.py

This issue arose from #509, due to somewhat complex details.
In short, the old `gvecToDetectorXY()` would filter out g-vectors going the wrong way (they would result in `nan`), but `gvecToDetectorXYArray()` would not.
The new `gvec_to_xy()` has behavior matching `gvecToDetectorXYArray()`. But that means that places where `gvecToDetectorXY()` used to be used, we need to verify that the function does not receive g-vectors going the wrong way.
Looking through the code, however, I only found one place where `gvecToDetectorXY()` used to receive g-vectors going the wrong way. It was the Laue overlay simulator, which would compute g-vectors from symmetrical HKLs (which is why it would have duplicate g-vectors going the wrong way).
All other cases where `gvecToDetectorXY()` was called would be …

Remove duplicate Laue spots from simulator

---

hexrd/imageseries/load/imagefiles.py

Apply a bitwise not operation before scaling the data. The scale factor was computed to be 2.945215294651886e-07 by @psavery and @saransh13. See [this comment](https://github.com/HEXRD/hexrdgui/issues/1387#issuecomment-1498177302) for more information.
Fixes HEXRD/hexrdgui#1387

Add support for .gel files

---

.github/workflows/package.yml

`set-output` is deprecated and will be removed soon. Try migrating over to using `GITHUB_ENV`.

Change GitHub Actions set-output to use GITHUB_ENV

---

tests/test_fit-grains.py

This updates tests following the HEXRD/examples#7, which changed the location of one of the data files.

update test to use new data location in examples repo

---

.github/workflows/package.yml

This needs to be done until [this issue is fixed](Anaconda-Platform/anaconda-client#654).

Downgrade urllib3 for anaconda-client

---

hexrd/fitting/calibration.py

Set the min and max to the absolute maximum allowed values. Handle the locations better if the separation falls outside this range.

handle the IP separations better.

---

hexrd/spacegroup.py
hexrd/unitcell.py
hexrd/wppf/LeBailCalibration.py
hexrd/wppf/RietveldHEDM.py
hexrd/wppf/WPPF.py
hexrd/wppf/parameters.py
hexrd/wppf/phase.py

`np.bool` was a deprecated alias for the built-in `bool`. Support for it was removed recently, and thus we really need to just use the built-in bool.
See: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Corresponding hexrdgui PR: hexrd/hexrdgui#1494
Fixes the issue mentioned in [this comment](https://github.com/HEXRD/hexrdgui/issues/1493#issuecomment-1583175760)

Change all cases of np.bool to just bool

---

conda.recipe/meta.yaml

Fabio uses lxml (it is optional, but installing fabio installs it by default).
On Windows, lxml 4.9.1 is causing the application to crash silently. There are no errors - the application just crashes when fabio is imported.
We need to force it to use lxml 4.9.2 or greater to avoid this crash. We could alternatively just stop it from being installed as well if we run into more issues in the future.

Use latest lxml

---

hexrd/transforms/xf.py
hexrd/unitcell.py
hexrd/wppf/LeBailCalibration.py
hexrd/wppf/RietveldHEDM.py
hexrd/wppf/WPPF.py
hexrd/wppf/parameters.py
hexrd/wppf/phase.py
pyproject.toml
setup.py
tests/test_find_orientations.py

See [here](https://numpy.org/doc/stable/release/1.24.0-notes.html).
The list of deprecated aliases is:
```
np.object, np.bool, np.float, np.complex, np.str, and np.int
```
Fixes: #533

Fix remaining deprecated numpy aliases

---

hexrd/instrument/cylindrical_detector.py
hexrd/instrument/planar_detector.py

This logic was not working before, and we needed to add the `_pixel_solid_angles` functions to the memoization size updates.
It appears to be working correctly now.

Fix memoization size updates for detectors

---

hexrd/instrument/detector.py

These will come out as invalid values anyways, which will be caught in
other parts of the code, so we don't need to see the warning.

Hide invalid pixel conversion warning

---

hexrd/resources/pxrdip_reference_config.yml

This is the most common polar angle that is used.

Change default polar angle for pxrdip to 67.5

---

setup.py

This change adds gcc compiler flags to optimize the runtime for the C API calls.
**Estimated performance increase: 10%**
Changes include:
- Add `-O3` to compiler flags for `transforms_CAPI.c`, `transforms_CFUNC.c`, `hexrd/transforms/new_capi/module.c`
- Add `-ftree-vectorize` to compiler flags for `transforms_CAPI.c`, `transforms_CFUNC.c`, `hexrd/transforms/new_capi/module.c`
Future proposed changes may include:
- Add the `-march=native` flag
- Add the `-mtune=native` flag

Build time performance optimization

---

hexrd/wppf/WPPF.py
hexrd/wppf/peakfunctions.py

Recently discovered a bug in the statistical weights and definition of goodness of fit (chi^2). This was causing chi^2 to be less than 1 which should not be the case. Fixing those bugs. 
Reference:
Brian H. Toby, R factors in Rietveld analysis: How good is good enough? Powder Diffraction 21(1), March 2006.

fix weights and definition of chi^2

---

hexrd/unitcell.py

make sure small rounding errors are dealt with correctly.

---

.github/workflows/container_build.sh
.github/workflows/package.yml

It is [officially supported by conda](https://www.anaconda.com/blog/conda-is-fast-now), and it is significantly faster.
Before this commit, Windows packaging usually takes 1 hour and 15 minutes. Mac packaging usually takes about 45 minutes. Linux usually takes about 35 minutes.
We'll see if there are any noticeable differences.
Fixes: #556

Try using libmamba solver for conda packaging

---

conda.recipe/meta.yaml
pyproject.toml
setup.py

If TBB is installed, numba will use TBB instead of OpenMP.
In my brief testing, it appears that having TBB makes some of the workflows run a little faster. It also fixes some warnings we have been seeing about OpenMP.

Add TBB as a dependency to HEXRD

---

hexrd/xrdutil/phutil.py

It was removed in the most recent version of numpy. We must use it from the `linalg` module instead.

Remove use of numpy.dual

---

.github/workflows/package.yml
.github/workflows/test.yml
conda.recipe/conda_build_config.yaml
conda.recipe/meta.yaml

Something like this should be possible...
Fixes: #499

Try cross-compiling for arm64 on osx

---

.github/workflows/package.yml
README.md

We are planning to combine the "hexrd-prerelease" and "hexrdgui-prerelease" channels into just "prerelease", so that the installations are simpler:
```bash
conda install -c hexrd/label/prerelease -c conda-forge hexrd
conda install -c hexrd/label/prerelease -c conda-forge hexrdgui
```

Change "hexrd-prerelease" label to "prerelease"

---

hexrd/transforms/xfcapi.py

As the title says. This is needed for the constant chi overlays.

import angs_to_dvec as well

---

hexrd/instrument/detector.py

The config is valid without the "roi". If the "roi" is None, we just should not include it at all.
This helps clean up the tree view a little bit in HEXRDGUI, so that there isn't an "roi" present when there is none.

Only include "roi" in the config if it is not None

---

scripts/install/install_build_dependencies.py
setup.py

We currently support 3 different build setups:
1. In a conda environment (uses pybind11 conda package in build step)
2. In a regular pip environment (uses pybind11 in build isolation as specified in pyproject.toml)
3. In a conda development environment (no build isolation)
This PR fixes number 3.
pybind11 is not a runtime dependency for the conda environment, so if a user installs the HEXRD prerelease, it won't come with pybind11. Then, if a user tries to make a dev environment, pybind11 won't be available.
The changes here make it so that in situation number 3, the pybind11 source code is downloaded automatically and installed, so that the headers can be found.
Fixes: #586   (see [here](https://github.com/HEXRD/hexrd/issues/586#issuecomment-1826404961))

Install pybind11 if it is missing

---

hexrd/config/__init__.py
hexrd/config/config.py
hexrd/imageseries/save.py
hexrd/instrument/hedm_instrument.py
hexrd/utils/yaml.py
hexrd/wppf/parameters.py
hexrd/wppf/phase.py
tests/test_utils_yaml.py

We want to make sure we avoid unsafe yaml dumps, which can be used to dump arbitrary Python objects, because want to avoid unsafe yaml loads, which can execute arbitrary Python code and is a security risk.
It looks like we were sometimes dumping numpy objects (as can be seen in hexrd/hexrdgui#1625), and these cannot be loaded without performing an unsafe load.
This PR changes all regular yaml dumps to `safe_dump` to ensure this does not happen. It also adds a custom dumper that converts numpy types to native types while dumping. This is used when saving the instrument config currently (but we can use it in other places too, if needed).
Fixes: hexrd/hexrdgui#1625

Add yaml dumper that converts numpy to native

---

hexrd/constants.py
hexrd/material.py
hexrd/unitcell.py

The material's (or unitcell's) point group can now be accessed via a `pgnum` property.
This also adds some dicts that store this info.

Add property for point group number to material

---

hexrd/instrument/detector.py
hexrd/instrument/hedm_instrument.py

For use cases (like ROI) where a single image may be associated with multiple detectors the "group" key can be included to indicate which detectors should be grouped together.

Add support for detector "group" key

---

hexrd/resources/detector_templates/dexela-2923-detector-subpanel.yml
hexrd/resources/detector_templates/dexela-2923-detector.yml

The current translation of [0, 0, 0] doesn't work well with HEXRDGUI, since it indicates that the detector is on top of the sample.
We should make the transform section optional instead. If it is not provided, then HEXRDGUI will insert the default transform section. This will make the views work better...
If some detectors typically have a certain transform, it can still be provided and that will be used instead of the default.

Remove transform section from these detectors

---

hexrd/material/crystallography.py
hexrd/material/material.py
hexrd/matrixutil.py
hexrd/utils/decorators.py

Fixes issue #595. The function is ~5-10x faster (after the first compile overhead).

numba accelerated findDuplicateVectors

---

hexrd/imageseries/process.py
tests/imageseries/common.py
tests/imageseries/test_process.py

When a `ProcessedImageSeries` is instantiated with a `frame_list`, it now checks the metadata for an `omega` key. If `omega` is present, then the metadata is updated appropriately.

ProcessedImageseries with frame_list automatically updates omega metadata

---

hexrd/imageseries/save.py
tests/imageseries/test_formats.py

This allows you to write an imageseries in `frame-cache` format without specfying the `cache_file` keyword argument.
Before this change, you would pass the `filename` argument as well as the the `cache_file`  keyword arg, usually the same value in both places. Now, the cache_file is determined from the filename.  
The history of this is that the original format for `frame-cache` was a YAML file for the metadata, and the imagefiles were stored as sparse arrays in a numpy npz file, the cache file.  Currently the default format is to save all image data and metadata both in the same file, so a separate cache file is not necessary.  
For the YAML format, the cache file (if not an absolute path) is taken relative to the YAML file, so any directory  is prepended to the cache file.  For the …

Frame cache writer

---

hexrd/imageseries/load/imagefiles.py

This pull request allows you to load an imageseries of type `image-files` by passing the yaml text directly to the `open() `command instead of writing it to a file first and then loading the file.  This is just a convenience for writing raw data processing scripts.
I also have a test file that verifies this, but since it involves a large data file, I chose not to submit it here.  I suggest we add an imageseries directory to the hexrd-examples repository, where we can take advantage of existing large data files.
Here is the test script: 
```import numpy as np
import pytest
from hexrd import imageseries
@pytest.fixture
def image_files_fmt():
return "image-files"
@pytest.fixture
def yaml_tmpl():
return """image-files:
directory: .
files: RUBY_*
options:
empty-frames: %(n_ef)d …
```

Imagefiles yaml text

---

setup.py

tbb is not available on PyPI for non-intel machines. Only include it as a requirement in the setup.py file for intel machines.

Remove tbb requirement for non-intel machines

---

hexrd/imageseries/load/rawimage.py
hexrd/imageseries/save.py
hexrd/instrument/hedm_instrument.py

This ensures that for multithreaded situations (such as writing out a frame cache), `__getitem__` will be thread-safe. The change ensures that the frame will be obtained immediately after seeking, and no other thread can seek until the frame is obtained.
When I test the example Darren gave us (#608) on the master branch with no multithreading, it ran in 5m 37s. With this change, and using multithreading, it ran in 5m 13s. So the multithreading produced a minor speed increase.
Fixes: #608

Make __getitem__ for raw imageseries threadsafe

---

hexrd/material/unitcell.py

This fixes a typo in `unitcell.MakeStiffnessMatrix`.  It also removes a code line in between two functions.
The whole stiffness matrix calculation could use some verification tests. @saransh13 
Fixes: #616

fixes stiffness matrix typo

---

.github/workflows/container_build.sh
.github/workflows/package.yml
hexrd/instrument/detector.py
hexrd/material/crystallography.py

This is computed nearly the same way as the powder intensity, except that it does not include multiplicity.
This PR also moves the lorentz and polarization functions to the crystallography module, where they are now used for computing the powder and HEDM intensities.

Add hedm_intensity to PlaneData

---

hexrd/projections/polar.py

An extra argument to `cylindrical_detector` was being passed. Fixed it.

fix arguments to cylindrical detector.

---

hexrd/instrument/detector.py

Removed unnecessary setting of large arrays, roughly 6% estimated speedup for caking scripts.

Do not set values to 0 that are not referenced.

---

hexrd/wppf/derivatives.py

Resolve the `hexrrd` typo in the wppf section.

Fix hexrd misspelling, resolves #622

---

hexrd/fitting/peakfunctions.py
hexrd/wppf/WPPF.py
hexrd/wppf/peakfunctions.py
hexrd/wppf/phase.py
hexrd/wppf/wppfsupport.py

- Add stacking fault probability, $\alpha$ and twin probability, $\beta$ to the `wppf` module.
- Made the particle size and micro strain terms phase dependent.
- Removed anisotropic broadening, Xe and Ye for simplification.

Stacking fault wppf

---

hexrd/resources/detector_templates/GE-detector.yml
hexrd/resources/detector_templates/Pilatus3X_2M-detector.yml
hexrd/resources/detector_templates/Pixirad2-detector.yml
hexrd/resources/detector_templates/Varex_4343CT-detector.yml
hexrd/resources/detector_templates/dexela-2923-detector-subpanel.yml
hexrd/resources/detector_templates/dexela-2923-detector.yml
hexrd/resources/instrument_templates/dual_dexelas.yml

Panel buffers of 1-2 mm are too big to use by default. We were running into some issues with these on another dataset.
It seems better to just not have a default panel buffer, so remove them.

Remove panel buffers from detector templates

---

hexrd/imageutil.py

According to the [scipy documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve.html#scipy.signal.convolve), `convolve` will automatically pick which method to use depending on which method it thinks will be faster.
We were forcing it to use `fftconvolve` before, which, for our example, took about 1.588 seconds to run. Switching to `convolve` now takes about 0.468 seconds instead, so it is noticeably faster.
In our example, the final snip1d result had a max difference of `2.6e-13` compared to using `fftconvolve`, so it appears to have a minimal impact on the results.

Use scipy's `convolve` for snip1d

---

.github/workflows/container_build.sh

Otherwise, wget is complaining that the certificates are expired when it tries to download miniconda from the anaconda website...

Update ca certificates for centos Linux build

---

hexrd/imageseries/load/imagefiles.py

fabio would perform some arithmetic with the frame number we provided it to compute byte offsets for GE images. On Windows, an `int` times a `np.int32` is an `np.int32`. If our frame number was `np.int32`, for large datasets, this would cause an overflow error, since int32 would be used for the byte offset. 
Instead, ensure a python integer is passed, which *cannot* overflow.

Fix integer overflow issue in fabio

---

.github/workflows/package.yml

This is the last version to use x86_64. The runners are starting to, by default, use arm64 (Apple silicon).

Downgrade packaging macos to 12

---

hexrd/fitting/calibration/instrument.py
hexrd/fitting/calibration/laue.py
hexrd/fitting/calibration/lmfit_param_handling.py
hexrd/fitting/calibration/structureless.py
hexrd/instrument/hedm_instrument.py

Some users strongly prefer to use a different Euler convention for calibration, such as extrinsic XYZ. It is easy to convert angles from one Euler convention to another. However, it is difficult to convert boundary conditions (min/max ranges for each angle) from one convention to another.
So we add the ability to choose the Euler convention to use in calibration. This allows the min/max ranges to be specified in lmfit using that convention.

Allow Euler convention setting for calibration

---

hexrd/findorientations.py

Set the `n_jobs` parameter of `dbscan()` to be the `cfg.multiprocessing`. This will allow dbscan to run in parallel. For very large numbers of orientations, this may provide a significant speedup.

Run dbscan in parallel

---

conda.recipe/conda_build_config.yaml
hexrd/imageseries/load/__init__.py
hexrd/imageseries/load/eiger_stream_v1.py
hexrd/instrument/hedm_instrument.py
hexrd/utils/hdf5.py

This supports our current eiger stream data files.
It would be really nice in the future if we figured out a way to get the data to just be regular datasets in the HDF5 file that are automatically decompressed on loading. But we will have to do this for now...

Add eiger-stream-v1 imageseries format

---

hexrd/rotations.py
tests/test_rotations.py

Updated docstring for rotations.misorientation and added pytest module for rotations.   In response to Discussion #643.

updated documentation for rotations.misorientation

---

hexrd/wppf/WPPF.py
hexrd/wppf/phase.py

The fix works provided all the phase fractions are refined simultaneously. The refinement of all phase fractions will be coupled in a future PR.

Rietveld phase fraction fix

---

hexrd/imageseries/load/__init__.py
hexrd/imageseries/load/function.py

This adds a highly customizable imageseries adapter that simply accepts a function and a number of frames. The function takes a single argument (an integer for the frame index), and returns a 2D numpy array for that frame.
This will be used for streaming in data, where the data is compressed in memory (not on disk), and the custom function simply decompresses the frame and returns it.
We will then use this to create a sparse data writer.

Add an imageseries adapter for arbitrary functions

---

hexrd/transforms/new_capi/xf_new_capi.py

Doc strings added in xf_new_capi.  Also fixed a bug in [xy_to_gvec](https://github.com/Verdant-Evolution/hexrd/blob/441912346cbea972f86b3f979d412befd7e4e2a8/hexrd/transforms/new_capi/xf_new_capi.py#L339C1-L342C1) where a variable name was incorrect.
The [make_binary_rmat](https://github.com/Verdant-Evolution/hexrd/blob/5287b0a553892ba111731d3f1864dff0a56666c0/hexrd/transforms/new_capi/xf_new_capi.py#L449C1-L454C39) function does not have a doc string as I could not find any documentation about it.  Is it necessary to keep around, or is it unused?
Also, in some testing, I found that the [unit_vector](https://github.com/Verdant-Evolution/hexrd/blob/5287b0a553892ba111731d3f1864dff0a56666c0/hexrd/transforms/new_capi/xf_new_capi.py#L343-L373) function is transposed as to what it was in the old …

Docstrings

---

.github/workflows/container_build.sh

CentOS 7 reached EOL 06/30/2024, and consequently mirrorlist.centos.org is no longer available. As detailed below, we would like to stay with CentOS 7 for now, so use the archive mirror instead.

Use archive mirror for CentOS 7

---

hexrd/fitgrains.py

Confirm this correctly understands what `grain_table` is.  This still passes the testcases, and if test_fitgrains is changed to remove the ndmin=2 (and making other necessary changes), it also passes, implying that this change does what it's supposed to do.
closes #677

Single grain fitting

---

hexrd/rotations.py
tests/rotations/test_eulers.py
tests/rotations/test_quat_math.py

Added some testcases for some of the math helpers in `rotations.py`.  Also fixed `quatProduct`, see [issue 684](https://github.com/HEXRD/hexrd/issues/684). After this PR confirms that the new testcases are working properly, I will rewrite some of these methods to use scipy.  I didn't want to change the methods at the same time as I added the testcases, because then there is no confirmation that the new implementations work.
closes #684

Rotations testcases

---

hexrd/material/unitcell.py
hexrd/wppf/xtal.py

remove unitcell.CalcAnomalous and unitcell.CalcXRayFormFactor. These functions have been replaced by numba function wppf.xtal._calcanomalousformfactor and wppf.xtal._calcxrayformfactor. Also removes the property `unitcell.Z`. 
Fixes: #683 
Fixes: #685

remove unused functions in unitcell

---

hexrd/material/material.py

fix error in fractional occupancy cases while reading cif file.

---

pyproject.toml
setup.py

Resolve compiler flags for Windows

---

.github/workflows/test.yml

The CI seems to be failing because of this...

Try removing fabio pin

---

hexrd/imageseries/load/framecache.py

Previously, just instantiating the imageseries would cause the data to be loaded. For some of the larger datasets from eiger, this could use a lot of RAM and time.
However, in some cases, we want to instantiate an imageseries just as a convenient (and somewhat standardized) way to look at things such as metadata (such as omegas) and other information without actually needing to load the data. This is actually something we do in the GUI to check the omegas (we do it for all image series types, in fact, not just frame-cache).
This commit changes the class to wait to load the data until it is actually requested. This makes loading it in the Simple Image Series loader in the GUI (which is done to check metadata) *significantly* faster.
This class still loads in all the frames the first time …

Lazily load the data in the frame-cache format

---

hexrd/rotations.py
hexrd/utils/warnings.py

We don't really need to see these, as they are not an issue for us. Hide the warnings.

Ignore Gimbal lock warnings from scipy

---

hexrd/findorientations.py

This is a one-line fix. The line
```
eta_ome.save(fn)
```
was changed to 
```
eta_ome.save_eta_ome_maps(fn)
```
in #663, which broke the `findorientations` example in NIST_RUBY/single_GE because, giving this error:
```
Traceback (most recent call last):
File "/Users/deboyce/Source/hexrd/pkg/hexrd/findorientations.py", line 422, in load_eta_ome_maps
res = EtaOmeMaps(fn)
File "/Users/deboyce/Source/hexrd/pkg/hexrd/xrdutil/utils.py", line 86, in __init__
ome_eta: np.ndarray = np.load(ome_eta_archive, allow_pickle=True)
File "/Users/deboyce/miniconda3/envs/hexrd-dev/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: …
```

fixes eta_ome.save() call in findorientaions.py

---

hexrd/material/material.py
hexrd/wppf/WPPF.py
hexrd/wppf/parameters.py

This removes the need to import matplotlib from the code.
Now, it expects the background points to have been pre-selected elsewhere,
and the background points is the single argument for the `spline` background
method.
Corresponding branch in the GUI: hexrd/hexrdgui#1728

Remove point selection from WPPF

---

hexrd/material/crystallography.py

This PR will replace some previously archived functions from the `hexrd/material/crystallography.py` script in the current pre-release.

Replace previously archived functions

---

hexrd/fitting/calibration/laue.py
hexrd/fitting/calibration/lmfit_param_handling.py
hexrd/fitting/calibration/powder.py
hexrd/fitting/calibration/structureless.py
hexrd/instrument/__init__.py
hexrd/instrument/hedm_instrument.py
hexrd/resources/tardis_2xrs_reference_config.yml
hexrd/resources/tardis_reference_config.yml
tests/test_2xrs_calibration.py

This adds support for multiple x-ray sources, which may have different beam vectors, energies, and distances.
This also adds support for calibrating to diffraction patterns from multiple x-ray sources, including for powder, Laue, and also structureless.

Add support for multiple x-ray sources

---

hexrd/xrdutil/phutil.py

fix pinhole corrections for edge cases. All variables for PXRDIP and TARDIS should be same now. No special treatment of PXRDIP data needed.

Fix pinhole offset corrections

---

conda.recipe/meta.yaml
hexrd/imageseries/load/framecache.py
hexrd/imageseries/save.py
setup.py
tests/imageseries/test_formats.py

The new format allows to store more complex datasets including  metadata at multiple levels.
The new fch5 file contains the following fields:
- `shape`,`nframes`,`dtype`  similar to before storing shape as tuple, nframes as integer and dtype of the imageseries as an encoded string.
- `data` an (m,1) array of type `dtype` holding the datavalues of all frames. `m` is evaluated on runtime based on `threshold` value
- `indices` an (m,2) array of type `np.uint16` holding the row and column indices of the datavalues for each frame.
- `frame_ids`: (2*nframes,1) holds the range that the i-th frame occupies in the above, i.e. the information of the i-th frame  can be accessed using:
```
data_i = data[frame_ids[2*i]:frame_ids[2*i+1]]
indices_i = indices[frame_ids[2*i]:frame_ids[2*i+1]]
```
Both the …

Add fch5 an hdf5-based format for storing framecaches

---

hexrd/instrument/detector.py

don't compute correction if no pinhole.

---

hexrd/gridutil.py

Suppresses an annoying error that kept popping up.
`/Users/soderlind3/hexrd/hexrd/gridutil.py:90: RuntimeWarning: invalid value encountered in cast
return np.array(idx, dtype=int)`

cast only non-nan numbers to integers. 

---

hexrd/imageseries/load/framecache.py
tests/imageseries/test_pickleable.py

The multiprocessing library uses pickle to serialize objects between processes. This
was creating an issue for FrameCacheImageSeries since it contained a non-pickleable attribute.
We now skip this from the state. This should not affect the functionality of the framecache since
it was used to make sure that only one thread was populating the cache at a time. The same is true
now. In every process only one thread at a time can populate the cache
Fixes: #731

Make framecache pickleable

---

.github/workflows/package.yml

The packaging on Mac is currently broken on master. There is an issue with the compatibility between libmamba and the version of libarchive.
See if we can fix it by removing the libarchive installation.

Try to not install libarchive separately

---

hexrd/cli/find_orientations.py
hexrd/cli/fit_grains.py
hexrd/config/config.py
hexrd/config/findorientations.py
hexrd/config/fitgrains.py
hexrd/config/material.py
hexrd/config/root.py
hexrd/findorientations.py
hexrd/fitgrains.py
tests/config/test_find_orientations.py
tests/config/test_root.py

The intention of this pull request is to make the output file placement in `find-orientations` and `fit-grains` cleaner and simpler while cleaning up computational code that has hardwired file names and file handling that would be better done elsewhere, _i. e._ the config module.
Roughly, this is what has been done:
- put output files in the `analysis_dir` instead of in the `working_dir` with long names based on the `analysis_name`
- allow for slashes in `analysis_name` and automatically create subdirectories as needed for the `analysis_dir`
- this is particularly useful when the config file has multiple (YAML) documents
- move path manipulations and hardwired file names from computational modules to the config module
- use pathlib for handling file and directory names
- update docstrings …

File placement improvements

---

hexrd/fitting/calibration/instrument.py
hexrd/fitting/calibration/lmfit_param_handling.py
hexrd/fitting/calibration/relative_constraints.py

For relative constraints, when tilts are applied to the detectors, the center of rotation is an additional setting that can be varied. Specifying a center of rotation that better matches what is expected in the experiment will result in calibrations with greater accuracy and speed.
For example, for FIDDLE, if there is any tilt whatsoever, then the detectors must have rotated about the lab origin (0, 0, 0). Requiring the detectors to be rotated about the origin ensures that the calibration will match what is expected from the experiment.
For other detector setups, such as the Eiger, the mean center of the instrument better matches what is expected if a tilt must be applied.

Add ability to specify center of rotation

---

.github/workflows/container_build.sh

There's some error in the Linux packaging related to anaconda telemetry, which is not really needed in our packaging (it just reports information to conda). Try disabling it to see if it fixes the packaging process...

Try removing anaconda telemetry to fix CI

---

hexrd/instrument/detector.py
hexrd/xrdutil/utils.py

It was assumed to be the default beam vector before, but we should allow it to be specified.

Add beam vector to simulateGVecs arguments

---

hexrd/xrdutil/utils.py

We were previously passing an array of matrices, and only the first matrix was being used in the old transforms code. In the new transforms code, an error is being raised because it expects only a single matrix (and not an array of matrices). We should explicitly only pass this first matrix to `angularPixelSize()`.

Only pass one rMat_s to angularPixelSize

---

hexrd/config/findorientations.py
hexrd/config/root.py
hexrd/findorientations.py
tests/config/test_find_orientations.py

This fixes some problems introduced in pull request #733. Fixes include:
1. default eta-omega maps filename
2. fixes argument name in `write_scored_orientations` function
3. cleans up the `working_dir` property in config.root

simple fixes 

---

hexrd/instrument/cylindrical_detector.py
hexrd/instrument/hedm_instrument.py
tests/calibration/test_calibration.py

For cylindrical detectors, we need to take into account the radius for calibration flags and parameters.
This uses the old, non-lmfit style for defining calibration flags and parameters. We will be able to eliminate all of this when we upgrade the HEDM calibration to use the new lmfit calibration style...
But for now, we need to maintain this.

Take into account radius for calibration params

---

hexrd/cli/main.py
hexrd/cli/preprocess.py
hexrd/preprocess/argument_classes_factory.py
hexrd/preprocess/preprocessors.py
hexrd/preprocess/profiles.py
hexrd/preprocess/yaml_internals.py
tests/test_preprocess.py

This MR integrates the preprocessor scripts into the main `hexrd` executable via anew subcommand.
Usage:
```
hexrd preprocess <profile>
```
for now we have two profiles `{eiger,dexelas}`.  Each profile comes with its own flags. 
Adding a new profile boils down to creating a new class derived from `PP_Base` that holds the logic of the preprocessor see `hexrd/preprocess/preprocessors.py` and creating a new profile that holds the cli flags which be done by deriving from `HexrdPPScript_Arguments`  see  `hexrd/preprocess/profiles.py`. The new profile will then become available as an option in `hexrd preprocess`.

Integrate preprocess scripts

---

.github/workflows/container_build.sh
.github/workflows/package.yml

conda_build >= 25.1.0 use .conda files by default
See https://docs.conda.io/projects/conda-build/en/latest/release-notes.html#enhancements
Alternatively we can adapt the rest of the step to expect `.conda` packages.

ci: force tar.bz2 packages

---

hexrd/instrument/hedm_instrument.py

`ValueError: cannot convert float NaN to integer` error was generated when running fast powder calibration on some configurations. Culprit was found to be some invalid pixels when searching for peaks. Masking out those peaks before searching.

fixes nan error in fast powder calibration

---

hexrd/fitting/calibration/lmfit_param_handling.py
hexrd/fitting/calibration/relative_constraints.py
hexrd/instrument/hedm_instrument.py
tests/calibration/test_group_relative_constraints.py
tests/calibration/test_instrument_relative_constraints.py

This adds group relative constraints to calibrations, which constrains groups of detectors to tilt/translate in the same way. Most often, this will be used to constrain subpanels of a detector with the detector itself (such as with Dexelas), after any misalignment has been determined.
A set of thorough tests were also added which verify that the relative tilts/translations between subpanels (both of the same detector and different detectors) match when they should match, and do not match when they should not match.

Add group ("Detector") relative constraints

---

hexrd/imageseries/load/eiger_stream_v1.py

All of the other imageseries adapters return a numpy dtype. Here, we were just returning a string representing a dtype. However, we should return a numpy dtype to be consistent with all of the other imageseries adapters as well.
This also fixes issues in other places in the code where it is assumed that a numpy dtype is returned from the imageseries.
Fixes: hexrd/hexrdgui#1780

Return numpy dtype from eiger-stream-v1

---

hexrd/instrument/detector.py

Some configurations have points on the detector which can intercept backscattered x-rays. These points should be masked out since no signal will be detected due to self-absorption of the physics package.

mask out diffracted beams which travel parallel to physics package surface or which are backscattered.

---

hexrd/constants.py
hexrd/instrument/detector.py
hexrd/material/utils.py

Add functionality to compute Compton scattering intensity on an instrument panel. This is useful for intensity corrections during liquid total scattering analysis. There were two main calculation needed for this:
1. absorption of the inelastically scattered photons by the sample and window. since the inelastically scattered photons lose energy, the attenuation length is angle dependent.
2. computation of incoherent scattering intensity for each detector pixel. this is done by interpolating the table in `resources/Anomalous.h5`.
3. helper function in `material.utils
There is some special handling needed when the window is `None` or the thickness is `0`, both of which are valid ways to omit the window from the calculation.

Compton scattering

---

.coveragerc
.github/workflows/test.yml
tests/calibration/test_laue_auto_pick.py
tests/common.py
tests/requirements-dev.txt
tests/test_laue.py

This PR addresses a couple of small testing related issues. 
Firstly, the recently introduced in #761 compare the results of the LAUE functions as ordered lists, when, in fact, the order is not neither guaranteed nor important. Here we change that comparison to first sort both arrays and then compare them so the order is ignored. 
Secondly the pytest-cov plugin doesn't count code that is running in a separate process like when using a ProcessPoolExecutor.
To address the `multiprocessing` coverage, we can configure a `.coveragerc` file like the following, `coverage` will automatically start a new trace for each process created.
```
[run]
concurrency = multiprocessing
parallel = true
sigterm = true
```
Then we need to change the coverage report generation script like the following:
```yaml …
```

Stable vector set comparison

---

hexrd/fitgrains.py

In the `fit_grains()` function, the parameter `write_spots_files` is used to determine whether to write spots files or not.
Changes in 62c07b5 and 5a88225 appear to have accidentally caused it to be ignored, however. Switch back to the previous variable, which is correctly updated according to whether the spots files should be written or not.

Only write spots files if indicated to do so

---

hexrd/imageseries/load/__init__.py
hexrd/imageseries/load/framecache.py
hexrd/imageseries/load/hdf5.py
hexrd/imageseries/process.py
hexrd/utils/hdf5.py

Provide optimized implementation for when applying the rectangle operator in an imageseries as its first operation. 
ImageSeriesAdapter class has a new method
```
def get_region(self, frame_idx: int, region: RegionType) -> np.ndarray:
r = region
return self[frame_idx][r[0][0]:r[0][1], r[1][0]:r[1][1]]
```
Derived classes can offer optimized implementations. 
only ```FrameCacheImageSeriesAdapter```  and ``HDF5ImageSeriesAdapter`` take advantage of this for now.
workflows utilizing `ProcessedImageSeries` should see a  speedup if they use the rectangle operation as their first operation.
Results running locally on a 1441 frame dataset
| format            | before (s) | after(s) | % improvement |
|-------------------|------------|----------|---------------|
| framecache (npz)  | 1020       | …

 Improve rectangle operation performance

---

hexrd/fitting/calibration/abstract_grain.py
hexrd/instrument/detector.py

It needed to check an object one level further down...

Fix distortion check

---

setup.py

It seems that the [issue](https://github.com/jamesrhester/pycifrw/issues/14) that caused us to pin it has been fixed.

Unpin pycifrw

---

hexrd/imageseries/baseclass.py
hexrd/imageseries/imageseriesabc.py
hexrd/imageseries/load/__init__.py
hexrd/imageseries/process.py

Sometimes (as is the case for `OmegaImageSeries`), `self._adapter` is itself an imageseries, rather than an imageseries adapter.
To handle this recursion, use a forwarding function on the `ImageSeries` base class to forward the call to its adapter (which, if the adapter is itself an imageseries, will then forward the call to its own adapter).
This fixes running [this example](https://github.com/HEXRD/examples/blob/master/NIST_ruby/multiruby_dexelas/include/mruby_config_composite_roi.yml).

Handle recursion in imageseries get_region()

---

hexrd/instrument/detector.py
hexrd/instrument/planar_detector.py

An error was discovered in the pinhole area correction based on the CeO2 data recorded on TARDIS. An extra `sec(beta)` factor was added to the correction published in Rygg et al., Rev. Sci. Instrum. 91, 043902 (2020). This PR makes that change. 
Another small modification was made to use the existing functionality in the `transforms` module to compute the `beta` angles. This streamlines the function.

Modified pinhole area correction

---

hexrd/instrument/hedm_instrument.py

The `ome_eval` comes from simulated rotation series angles, and may not be the best thing to use as a reference point when computing measured omega values. We've had a hard time figuring out why it is being used. The measurement of a spot's omega value should ideally not depend on the current instrument calibration.
Instead, it seems better to use the code that is commented out immediately above it, which uses omega edges from the frame data as a reference point when computing measured omega values.
We have some new spot detection code (not in this repository) that also measures omega values, and our new spot detection code is in much greater agreement with `pull_spots()` if we implement this change. That provides further evidence as well that this change produces more accurate omega …

Fix calculation of measured omega values

---

hexrd/instrument/hedm_instrument.py
hexrd/wppf/WPPF.py

Spotted two errors:
1. the size of stacking fault shifts and stacking fault broadening not the same
2. the angularpixelsize has a zeros which was taken as the angular resolution. masking out zeros in those values.

some fixes for simulating powder diffraction pattern on an instrument.

---

hexrd/imageseries/load/hdf5.py

Previously, the HDF5 file would always be closed automatically. However, this presents a problem if there are multiple imageseries using the same file handle, and one of them is deleted, because the file will be closed and the other imageseries will become invalid.
This is particularly important for state files in the GUI, where there are many images saved within a single HDF5 state file, and if a user removes one detector, the file would be closed automatically and the other image series would become invalid.
This PR adds the ability to prevent automatic closing of the file when the imageseries is finished. `close_when_finished` is an optional keyword argument that defaults to `True` if missing. It fixes the issue with HDF5 state files.

Add option for closing file in HDF5 imageseries

---

hexrd/instrument/cylindrical_detector.py
hexrd/instrument/detector.py

Two bug fixes in this PR:
1. fix missing bvec argument from cylindrical detectors, same as the planar detectors.
2. fix runtime warning for pinhole effective area correction due to `sqrt` of a negative number.

Fix some bugs with the detector class

---

.github/workflows/test.yml
hexrd/material/material.py

Resolves issue #769. `SafeConfigParser` is removed in Python 3.12.
See source code here: https://github.com/python/cpython/blob/v3.11.1/Lib/configparser.py#L1242-L1252
Fixes: #769

Use ConfigParser instead of deprecated SafeConfigParser

---

hexrd/wppf/WPPF.py

WPPF module had a few edge case issues that showed up in the Rietveld and LeBail methods. This was leading to errors when the spline background method was being used. This PR fixes those issues.
There was an additional bug when more reflections were selected in the material than allowed by the X-ray wavelength or the detector coverage. This issue has also been fixed.

WPPF fixes

---

hexrd/fitting/calibration/structureless.py

Make the residual for structureless consistent with the composite calibration. An average of the error is returned instead of the total cumulative error.

Structureless residual

---

hexrd/instrument/detector_coatings.py
hexrd/instrument/physics_package.py

For both detector coating layers and physics package layers, allow a chemical formula to be provided.
This fixes an issue where you previously always had to provide the chemical formula for the material name. Now, you can provide other names such as `diamond` and the chemical formula can be provided separately (for example, `C8`) to be used for absorption correction calculations.

Add chemical formula to layer properties

---

hexrd/instrument/cylindrical_detector.py
hexrd/instrument/detector.py
hexrd/instrument/planar_detector.py
tests/test_pixel_solid_angles.py

Simplify the solid angle calculation using the first principle definition. For a surface of area, $\Delta$ at a location, $\mathbf{r}$ from the diffracting volume, the solid angle, $\mathrm{d}\Omega$ is given by:
$\mathrm{d}\Omega = \left(\frac{\Delta}{\vert \mathbf{r}\vert^{3}}\right)\mathbf{r}\cdot\hat{\mathbf{n}}$. 
$\hat{\mathbf{n}}$ is the local normal of the surface. Using this definition instead of summing over the areas of the triangle improves the speed by 2 orders of magnitude.

Solid angle speedup

---

hexrd/fitting/calibration/lmfit_param_handling.py

lmfit parameters cannot contain '-', or they produce an error.
Both the detector names and material names are user-defined, and they can contain '-' if the user adds it. We need to make sure we convert those to '_' in parameter names, though, so that lmfit will accept them.
We were already doing this for detector names, and we just needed to add this sanitization for material names as well.
Fixes: hexrd/hexrdgui#1875

Ensure lmfit parameters don't contain '-'

---

hexrd/fitting/grains.py
hexrd/imageseries/load/framecache.py
hexrd/imageseries/load/hdf5.py
hexrd/imageseries/load/imagefiles.py
hexrd/imageseries/load/rawimage.py
hexrd/imageseries/process.py
hexrd/instrument/hedm_instrument.py

Profiling showed that the list comprehension in `objFuncFitGrain` was taking a significant amount of time. This is because that function is called repeatedly during the least squares fit, and repeatedly performing the list comprehension would take a substantial amount of time.
Performing the list comprehension outside of `objFuncFitGrain` was shown to provide a substantial speedup.
This is something I discovered when I was working on the spot tracking code. I'm simply cherry-picking that commit here.
This only affects the fitting part, and not the `pull_spots()` part.

Significantly improve fit-grains performance

---

hexrd/fitgrains.py
hexrd/imageseries/load/hdf5.py
hexrd/imageseries/load/imagefiles.py
hexrd/imageseries/load/rawimage.py

A while back, we started lazily loading the data when a frame-cache imageseries was opened. This was so that a user could open an imageseries and investigate things like the shape and metadata before actually performing the data load.
For the CLI running fit grains, however, the data preload can be very helpful, because all the processes in the multiprocessing can share the loaded data if `fork` multiprocessing is being used (such as is the case for Linux).
We restore that behavior in this PR.
Before this PR, a frame cache that required 70 GB of RAM to load in the sparse arrays (which is not uncommon) would end up being loaded separately on every process, which would result in 70 GB times the number of processes of RAM being taken up (easily requiring terabytes of RAM).
Now, we ensure the …

Preload data for CLI fit-grains

---

hexrd/fitting/calibration/grain.py
hexrd/fitting/calibration/lmfit_param_handling.py
hexrd/fitting/grains.py
hexrd/instrument/detector.py
hexrd/instrument/hedm_instrument.py
hexrd/xrdutil/utils.py

This allows a slope (in eV/mm), intercept (in mm), and axis ('x' or 'y') to be specified for a beam energy correction according to grain positions.
This is important to take into consideration gradients in the beam energy profile, such that some grains may "experience" a different beam energy than others.

Add beam energy correction to grains

---

hexrd/wppf/WPPF.py
hexrd/wppf/amorphous.py
hexrd/wppf/peakfunctions.py
hexrd/wppf/texture.py
hexrd/wppf/wppfsupport.py
tests/test_wppf_amorphous.py

The WPPF module lacked a model to deal with cases where diffraction from both crystalline and amorphous diffraction are present. This PR addresses this deficiency by including 3 amorphous diffraction models:
1. An asymmetric split-gaussian peak shape
2. An asymmetric split-pseudo flight peak shape
3. a liquid profile which is experimentally measured
The first two peak shapes are implemented as `numba` accelerated function in `WPPF.peakshapes` module. The set of refinement parameters are different for the three models. Additional changes have been made to `WPPF.wppfsupport` module to deal with this. An example fit for Ti is shown below
None

Liquid model wppf

---

hexrd/fitting/calibration/instrument.py

It doesn't make sense for an instrument calibrator to have tth_distortion properties, because each modal calibrator inside might have a different `tth_distortion` dict.
To avoid confusion, just remove this property.

Remove tth_distortion properties from calibrator

---

hexrd/instrument/detector.py
hexrd/projections/polar.py

Most of these speedups are applicable for generating a whole bunch of polar view in a row with the same image (i. e., `cache_coordinate_map=True` when instantiating the `PolarView` class), but a few of them also improve performance of creating the `PolarView` in general.
Overall, we achieved at least a 10x speedup (in serial) for generating a bunch of images in a row, and even more of a speedup for some examples. A list of the improvements are as follows:
1. Using a "moving sum" for summing the detector images. This is particularly valuable for when you have many detectors (i. e., 32 subpanel Eiger). It eliminated the requirement of stacking all the images together before performing the sum, and we can instead discard images immediately after they are included in the sum.
2. Precompute …

Implement several speedups for polar view generation
